@extends('layouts.admin')
@section('title','Add Customer') @section('heading','Register Customer') @section('subheading','Create the customer and first service requirement in one transaction.')
@section('content')
@if(session('duplicate_customer_id'))<div class="mb-6 rounded-2xl border border-amber-300 bg-amber-50 p-5 text-amber-900"><strong>A customer with this mobile number already exists.</strong><p class="mt-1 text-sm">Existing record: {{ session('duplicate_customer_code') }}. Review it before creating a shared-contact duplicate.</p><div class="mt-4 flex flex-wrap gap-2"><a class="btn-secondary" href="{{ route('admin.customers.show',session('duplicate_customer_id')) }}">View Existing Customer</a><a class="btn-secondary" href="{{ route('admin.customers.requirements.create',session('duplicate_customer_id')) }}">Add New Requirement</a><button class="btn-primary" type="submit" form="registrationForm" name="force_duplicate" value="1">Create Duplicate Anyway</button></div></div>@endif
<form id="registrationForm" method="POST" action="{{ route('admin.customers.store') }}">@csrf
<div class="card mb-6 overflow-x-auto p-2"><div class="flex min-w-max gap-1">@foreach(['customer'=>'1. Customer','requirement'=>'2. Service','household'=>'3. House & Family','accommodation'=>'4. Accommodation','working'=>'5. Working Conditions','preferences'=>'6. Preferences','review'=>'7. Review'] as $step=>$label)<button type="button" data-step-button="{{ $step }}" class="rounded-xl px-3 py-2.5 text-sm font-bold text-neutral-500 first:bg-charcoal-900 first:text-white">{{ $label }}</button>@endforeach</div></div>
<section data-step-panel="customer" class="card p-6 md:p-8"><h2 class="mb-5 text-lg font-black">Customer Details</h2><div class="grid gap-5 md:grid-cols-2 lg:grid-cols-3"><div><label>Customer Code</label><input readonly value="Generated after save"></div><div><label>Registration Date</label><input required type="date" name="registration_date" value="{{ old('registration_date',today()->format('Y-m-d')) }}"></div><div><label>Registration Number</label><input name="registration_number" value="{{ old('registration_number') }}"></div><div><label>Customer Name</label><input required name="name" value="{{ old('name') }}"></div><div><label>Mobile Number</label><input required name="mobile_number" value="{{ old('mobile_number') }}"></div><div><label>Alternate Mobile</label><input name="alternate_mobile_number" value="{{ old('alternate_mobile_number') }}"></div><div><label>Email</label><input type="email" name="email" value="{{ old('email') }}"></div><div><label>Location</label><input name="location" value="{{ old('location') }}"></div><div><label>City</label><input name="city" value="{{ old('city') }}"></div><div class="md:col-span-2"><label>Address Line 1</label><input name="address_line_1" value="{{ old('address_line_1') }}"></div><div><label>Address Line 2</label><input name="address_line_2" value="{{ old('address_line_2') }}"></div><div><label>State</label><input name="state" value="{{ old('state') }}"></div><div><label>Pincode</label><input name="pincode" value="{{ old('pincode') }}"></div><div><label>Country</label><input required name="country" value="{{ old('country','India') }}"></div><div><label>Status</label><select name="status">@foreach($customerStatuses as $status)<option value="{{ $status->value }}" @selected(old('status','active')===$status->value)>{{ $status->label() }}</option>@endforeach</select></div><div class="md:col-span-2 lg:col-span-3"><label>Notes</label><textarea name="notes" rows="3">{{ old('notes') }}</textarea></div></div></section>
@include('admin.customer-requirements._fields',['registration'=>true,'statuses'=>\App\Enums\RequirementStatus::cases(),'experiences'=>\App\Enums\ExperienceRequirement::cases()])
<section data-step-panel="review" class="card hidden p-6 md:p-8"><h2 class="text-lg font-black">Review & Submit</h2><p class="mt-2 text-sm text-neutral-500">Review each section using the steps above. Your customer, requirement, household, accommodation, working conditions, and preferences will be saved together.</p><div id="reviewSummary" class="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"></div><button class="btn-primary mt-7" type="submit">Register Customer & Requirement</button></section>
<div class="mt-6 flex justify-between"><button id="previousStep" type="button" class="btn-secondary">Previous</button><button id="nextStep" type="button" class="btn-primary">Next</button></div></form>
@include('admin.customer-requirements._form-script')
@endsection
