@extends('layouts.admin')
@section('title','Customers') @section('heading','Customers') @section('subheading','Customer records and their latest service requirement.')
@section('actions')
@if(auth()->user()->hasPermission('customers.create'))<a class="btn-primary" href="{{ route('admin.customers.create') }}">+ Add Customer</a>@endif
@endsection
@section('content')
<form class="card mb-6 grid gap-3 p-4 sm:grid-cols-2 lg:grid-cols-5" method="GET"><input name="search" value="{{ request('search') }}" placeholder="Code, name, mobile, email, city"><select name="status"><option value="">All statuses</option>@foreach($statuses as $status)<option value="{{ $status->value }}" @selected(request('status')===$status->value)>{{ $status->label() }}</option>@endforeach</select><select name="city"><option value="">All cities</option>@foreach($cities as $city)<option @selected(request('city')===$city)>{{ $city }}</option>@endforeach</select><input type="date" name="registration_date" value="{{ request('registration_date') }}"><div class="flex gap-2"><button class="btn-primary flex-1">Filter</button><a class="btn-secondary" href="{{ route('admin.customers.index') }}">Clear</a></div></form>
<div class="card overflow-x-auto"><table class="w-full min-w-[980px] text-left text-sm"><thead class="bg-neutral-50 text-xs uppercase text-neutral-500"><tr>@foreach(['Customer Code','Customer Name','Mobile','City','Required Service','Duty Type','Requirement Status','Registered','Actions'] as $h)<th class="px-4 py-3">{{ $h }}</th>@endforeach</tr></thead><tbody class="divide-y">@forelse($customers as $customer)@php($active=$customer->requirements->first(fn($r)=>in_array($r->requirement_status->value,\App\Enums\RequirementStatus::openStatuses())) ?? $customer->requirements->first())<tr><td class="px-4 py-4 font-bold">{{ $customer->customer_code }}</td><td class="px-4 py-4">{{ $customer->name }}</td><td class="px-4 py-4">{{ $customer->mobile_number }}</td><td class="px-4 py-4">{{ $customer->city ?: '—' }}</td><td class="px-4 py-4">{{ $active?->service?->name ?: '—' }}</td><td class="px-4 py-4">{{ $active?->dutyType?->name ?: '—' }}</td><td class="px-4 py-4">@if($active)<span class="{{ $active->requirement_status->badgeClass() }}">{{ $active->requirement_status->label() }}</span>@else — @endif</td><td class="px-4 py-4">{{ $customer->registration_date->format('d M Y') }}</td><td class="px-4 py-4"><div class="flex gap-2"><a class="font-bold text-gold-500" href="{{ route('admin.customers.show',$customer) }}">View</a>@if(auth()->user()->hasPermission('customers.edit'))<a href="{{ route('admin.customers.edit',$customer) }}">Edit</a>@endif @if(auth()->user()->hasPermission('customer-requirements.create'))<a href="{{ route('admin.customers.requirements.create',$customer) }}">Add requirement</a>@endif</div></td></tr>@empty<tr><td colspan="9" class="px-4 py-12 text-center text-neutral-500">No customers found.</td></tr>@endforelse</tbody></table></div><div class="mt-5">{{ $customers->links() }}</div>
@endsection
