@extends('layouts.admin')
@section('title', $customer->name)
@section('heading', $customer->name)
@section('subheading', $customer->customer_code)
@section('actions')<div class="flex gap-2">@if(auth()->user()->hasPermission('customer-requirements.create'))<a class="btn-primary" href="{{ route('admin.customers.requirements.create', $customer) }}">+ Add Requirement</a>@endif @if(auth()->user()->hasPermission('customers.edit'))<a class="btn-secondary" href="{{ route('admin.customers.edit', $customer) }}">Edit Customer</a>@endif</div>@endsection
@section('content')
<div class="card mb-6 overflow-x-auto p-2"><div class="flex min-w-max gap-1">@foreach(['overview'=>'Overview','requirements'=>'Requirements','documents'=>'Documents','assignments'=>'Assignments','agreements'=>'Agreements','invoices'=>'Invoices','payments'=>'Payments','replacements'=>'Replacement History','contact'=>'Contact / Address','activity'=>'Activity'] as $tab=>$label)@if($tab==='invoices'&&!auth()->user()->hasPermission('invoices.view'))@continue @endif @if($tab==='payments'&&!auth()->user()->hasPermission('payments.view'))@continue @endif @if($tab==='documents'&&!auth()->user()->hasPermission('customer-registration-documents.view'))@continue @endif<button type="button" data-tab-button="{{ $tab }}" class="rounded-xl px-4 py-2.5 text-sm font-bold text-neutral-500 first:bg-charcoal-900 first:text-white">{{ $label }}</button>@endforeach</div></div>
<section data-tab-panel="overview" class="card p-6"><div class="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">@foreach([['Customer Code',$customer->customer_code],['Name',$customer->name],['Mobile',$customer->mobile_number],['Alternate Mobile',$customer->alternate_mobile_number],['Email',$customer->email],['Registration Date',$customer->registration_date?->format('d M Y')],['Status',$customer->status->label()],['Total Requirements',$customer->requirements->count()]] as [$label,$value])<div><p class="text-xs font-bold uppercase text-neutral-400">{{ $label }}</p><p class="mt-1 font-semibold">{{ $value ?: '—' }}</p></div>@endforeach</div></section>
<section data-tab-panel="requirements" class="card hidden divide-y">@forelse($customer->requirements as $requirement)<a class="flex justify-between p-4" href="{{ route('admin.customer-requirements.show', $requirement) }}"><span><strong>{{ $requirement->requirement_code }}</strong> · {{ $requirement->service?->name }} · {{ $requirement->dutyType?->name ?: 'No duty type' }}</span><span>{{ $requirement->requirement_status->label() }}</span></a>@empty<p class="p-6">No requirements.</p>@endforelse</section>
<section data-tab-panel="documents" class="card hidden p-6"><div class="mb-4 flex flex-wrap items-center justify-between gap-2"><h2 class="font-black">Customer Documents</h2>@if($customer->requirements->count()===1&&auth()->user()->hasPermission('customer-registration-documents.generate'))<a class="btn-primary" href="{{ route('admin.customers.registration-form.preview', $customer) }}">Generate Registration Form</a>@endif</div><div class="max-w-full overflow-x-auto"><table class="w-full min-w-[750px] text-left text-sm"><thead><tr><th class="p-3">Type</th><th class="p-3">Document Number</th><th class="p-3">Requirement</th><th class="p-3">Version</th><th class="p-3">Date</th><th class="p-3">Status</th><th class="p-3">Actions</th></tr></thead><tbody>@forelse($customer->generatedDocuments as $document)<tr class="border-t"><td class="p-3">{{ $document->document_type->label() }}</td><td>{{ $document->document_number }}</td><td>{{ $document->requirement?->requirement_code }}</td><td>v{{ $document->version_number }}</td><td>{{ $document->generated_at?->format('d M Y') ?: '—' }}</td><td>{{ $document->status->label() }}</td><td><a href="{{ route('admin.customer-generated-documents.show', $document) }}">View</a></td></tr>@empty<tr><td colspan="7" class="p-6">No customer registration forms.</td></tr>@endforelse</tbody></table></div></section>
<section data-tab-panel="assignments" class="card hidden overflow-x-auto"><table class="w-full min-w-[700px] text-left text-sm"><thead><tr>@foreach(['Assignment','Worker','Service','Start','End','Status'] as $header)<th class="px-4 py-3">{{ $header }}</th>@endforeach</tr></thead><tbody>@forelse($customer->assignments as $assignment)<tr><td class="px-4 py-3"><a href="{{ route('admin.assignments.show', $assignment) }}">{{ $assignment->assignment_code }}</a></td><td>{{ $assignment->worker?->name }}</td><td>{{ $assignment->service?->name }}</td><td>{{ $assignment->assignment_start_date?->format('d M Y') }}</td><td>{{ $assignment->assignment_end_date?->format('d M Y') ?: '—' }}</td><td>{{ $assignment->status->label() }}</td></tr>@empty<tr><td colspan="6" class="p-6">No assignments.</td></tr>@endforelse</tbody></table></section>
<section data-tab-panel="agreements" class="card hidden divide-y">@forelse($customer->agreements as $agreement)<a class="flex justify-between p-4" href="{{ route('admin.agreements.show', $agreement) }}"><span><strong>{{ $agreement->agreement_code }}</strong> · {{ $agreement->worker_name_snapshot ?: 'No worker' }} · {{ $agreement->service?->name ?: 'Service' }}</span><span>{{ $agreement->status->label() }}</span></a>@empty<p class="p-6">No agreements.</p>@endforelse</section>
<section data-tab-panel="invoices" class="card hidden p-6"><h2 class="mb-4 font-black">Invoices</h2><div class="max-w-full overflow-x-auto"><table class="w-full min-w-[650px] text-left text-sm"><thead><tr>@foreach(['Invoice','Date','Service','Total','Paid','Balance','Status'] as $header)<th class="p-3">{{ $header }}</th>@endforeach</tr></thead><tbody>@forelse($customer->invoices as $invoice)<tr class="border-t"><td class="p-3"><a href="{{ route('admin.invoices.show', $invoice) }}">{{ $invoice->invoice_number }}</a></td><td>{{ $invoice->invoice_date?->format('d M Y') }}</td><td>{{ $invoice->assignment?->service?->name ?: '—' }}</td><td>₹{{ $invoice->total_amount }}</td><td>₹{{ $invoice->paid_amount }}</td><td>₹{{ $invoice->balance_amount }}</td><td>{{ $invoice->effectivePaymentStatus()->label() }}</td></tr>@empty<tr><td colspan="7" class="p-6">No invoices.</td></tr>@endforelse</tbody></table></div></section>
<section data-tab-panel="payments" class="card hidden p-6"><h2 class="mb-4 font-black">Payments</h2><div class="max-w-full overflow-x-auto"><table class="w-full min-w-[700px] text-left text-sm"><thead><tr><th class="p-3">Payment Code</th><th class="p-3">Invoice</th><th class="p-3">Date</th><th class="p-3">Mode</th><th class="p-3">Amount</th><th class="p-3">Receipt</th></tr></thead><tbody>@forelse($customer->payments as $payment)<tr class="border-t"><td class="p-3"><a href="{{ route('admin.payments.show', $payment) }}">{{ $payment->payment_code }}</a></td><td>{{ $payment->invoice?->invoice_number }}</td><td>{{ $payment->payment_date?->format('d M Y') }}</td><td>{{ $payment->payment_mode->label() }}</td><td>₹{{ $payment->amount }}</td><td>@if($payment->receipt)<a href="{{ route('admin.payment-receipts.show', $payment->receipt) }}">{{ $payment->receipt->receipt_number }}</a>@else—@endif</td></tr>@empty<tr><td colspan="6" class="p-6">No payments.</td></tr>@endforelse</tbody></table></div></section>
<section data-tab-panel="replacements" class="card hidden divide-y">@forelse($customer->replacementRequests as $replacement)<a class="block p-4" href="{{ route('admin.replacements.show', $replacement) }}"><strong>{{ $replacement->replacement_code }}</strong> · {{ $replacement->oldWorker?->name }} → {{ $replacement->newWorker?->name ?: 'Pending' }}<span class="float-right">{{ $replacement->status->label() }}</span></a>@empty<p class="p-6">No replacements.</p>@endforelse</section>
<section data-tab-panel="contact" class="card hidden p-6"><div class="grid gap-5 sm:grid-cols-2">@foreach([['Address Line 1',$customer->address_line_1],['Address Line 2',$customer->address_line_2],['Location',$customer->location],['City',$customer->city],['State',$customer->state],['Pincode',$customer->pincode],['Country',$customer->country],['Notes',$customer->notes]] as [$label,$value])<div><p class="text-xs font-bold uppercase text-neutral-400">{{ $label }}</p><p class="mt-1">{{ $value ?: '—' }}</p></div>@endforeach</div></section>
<section data-tab-panel="activity" class="card hidden divide-y">@forelse($activities as $activity)<div class="p-4"><strong>{{ $activity->description }}</strong><p class="text-xs text-neutral-500">{{ $activity->user?->name ?: 'System' }} · {{ $activity->created_at->format('d M Y, h:i A') }}</p></div>@empty<p class="p-6 text-neutral-500">No activity recorded.</p>@endforelse</section>
<script>document.querySelectorAll('[data-tab-button]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab-button]').forEach(x=>x.className='rounded-xl px-4 py-2.5 text-sm font-bold text-neutral-500');b.className='rounded-xl bg-charcoal-900 px-4 py-2.5 text-sm font-bold text-white';document.querySelectorAll('[data-tab-panel]').forEach(p=>p.classList.toggle('hidden',p.dataset.tabPanel!==b.dataset.tabButton))})</script>
@endsection
