@extends('layouts.admin')
@section('title','Dashboard') @section('heading','Dashboard') @section('subheading','Live customer and service requirement overview.')
@section('content')
<section class="mb-6 overflow-hidden rounded-3xl bg-charcoal-900 p-7 text-white shadow-lg md:p-9"><p class="mb-3 text-sm font-bold text-gold-400">Welcome, {{ auth()->user()->name }}</p><h2 class="text-2xl font-black md:text-3xl">Home-care operations at a glance.</h2><p class="mt-3 text-neutral-400">Customer and requirement totals below are calculated from live records.</p></section>
<div class="grid gap-5 sm:grid-cols-2 xl:grid-cols-4">@foreach([['Total Customers',$totalCustomers],['Active Customers',$activeCustomers],['Open Requirements',$openRequirements],['New Requirements',$newRequirements]] as [$label,$value])<article class="card p-6"><p class="text-sm font-semibold text-neutral-500">{{ $label }}</p><p class="mt-3 text-4xl font-black">{{ $value }}</p></article>@endforeach</div>
@if(auth()->user()->hasPermission('enquiries.view'))<div class="mt-5 grid gap-5 sm:grid-cols-2 xl:grid-cols-4">@foreach([['New Enquiries',$newEnquiries],['Today’s Enquiries',$todayEnquiries],['Pending Follow-Ups',$pendingFollowUps],['Qualified Enquiries',$qualifiedEnquiries]] as [$label,$value])<article class="card p-5"><p class="text-sm font-semibold text-neutral-500">{{ $label }}</p><p class="mt-2 text-3xl font-black">{{ $value }}</p></article>@endforeach</div>@endif
<div class="mt-5 grid gap-5 sm:grid-cols-2 xl:grid-cols-4">@foreach([['Total Workers',$totalWorkers],['Available Workers',$availableWorkers],['Workers Working',$workingWorkers],['Verified Workers',$verifiedWorkers]] as [$label,$value])<article class="card p-5"><p class="text-sm font-semibold text-neutral-500">{{ $label }}</p><p class="mt-2 text-3xl font-black">{{ $value }}</p></article>@endforeach</div>
<div class="mt-5 grid gap-5 sm:grid-cols-2 xl:grid-cols-4">@foreach([['Active Assignments',$activeAssignments],['Workers Currently Working',$workingWorkers],['Open Worker Searches',$openWorkerSearches],['Pending Replacements',$pendingReplacements]] as [$label,$value])<article class="card p-5"><p class="text-sm font-semibold text-neutral-500">{{ $label }}</p><p class="mt-2 text-3xl font-black">{{ $value }}</p></article>@endforeach</div>
<div class="mt-5 grid gap-5 sm:grid-cols-2 xl:grid-cols-4">@foreach([['Total Agreements',$totalAgreements],['Draft Agreements',$draftAgreements],['Pending Signature',$pendingSignatureAgreements],['Active Agreements',$activeAgreements]] as [$label,$value])<article class="card p-5"><p class="text-sm font-semibold text-neutral-500">{{ $label }}</p><p class="mt-2 text-3xl font-black">{{ $value }}</p></article>@endforeach</div>
<div class="mt-6 grid gap-6 xl:grid-cols-2"><section class="card overflow-hidden"><div class="border-b p-5"><h3 class="font-black">Recent Customers</h3></div><div class="divide-y">@forelse($recentCustomers as $customer)<a class="flex justify-between gap-3 p-4 hover:bg-neutral-50" href="{{ route('admin.customers.show',$customer) }}"><span><strong class="block">{{ $customer->name }}</strong><small class="text-neutral-500">{{ $customer->customer_code }}</small></span><span class="text-sm text-neutral-500">{{ $customer->registration_date->format('d M Y') }}</span></a>@empty<p class="p-5 text-sm text-neutral-500">No customers yet.</p>@endforelse</div></section><section class="card overflow-hidden"><div class="border-b p-5"><h3 class="font-black">Recent Requirements</h3></div><div class="divide-y">@forelse($recentRequirements as $item)<a class="flex justify-between gap-3 p-4 hover:bg-neutral-50" href="{{ route('admin.customer-requirements.show',$item) }}"><span><strong class="block">{{ $item->service->name }} · {{ $item->customer->name }}</strong><small class="text-neutral-500">{{ $item->requirement_code }}</small></span><span class="{{ $item->requirement_status->badgeClass() }}">{{ $item->requirement_status->label() }}</span></a>@empty<p class="p-5 text-sm text-neutral-500">No requirements yet.</p>@endforelse</div></section></div>
@if(auth()->user()->hasPermission('billing.view'))<div class="mt-5 grid gap-5 sm:grid-cols-2 xl:grid-cols-4">@foreach([['Total Invoices',$totalInvoices],['Unpaid Amount','₹'.number_format((float)$unpaidAmount,2)],['Paid Amount','₹'.number_format((float)$paidAmount,2)],['Overdue Amount','₹'.number_format((float)$overdueAmount,2)]] as [$label,$value])<article class="card p-5"><p class="text-sm font-semibold text-neutral-500">{{ $label }}</p><p class="mt-2 text-3xl font-black">{{ $value }}</p></article>@endforeach</div>@endif
@if(auth()->user()->hasPermission('billing.payments.view'))<div class="mt-5 grid gap-5 sm:grid-cols-2 xl:grid-cols-4">@foreach([['Payments Received Today','₹'.number_format((float)$paymentsToday,2)],['Payments This Month','₹'.number_format((float)$paymentsThisMonth,2)],['Outstanding Balance','₹'.number_format((float)$outstandingBalance,2)],['Pending / Unpaid Invoices',$pendingInvoices]] as [$label,$value])<article class="card p-5"><p class="text-sm font-semibold text-neutral-500">{{ $label }}</p><p class="mt-2 text-3xl font-black">{{ $value }}</p></article>@endforeach</div>@endif
<div class="mt-6 grid gap-6 xl:grid-cols-2"><section class="card overflow-hidden"><div class="flex items-center justify-between border-b p-5"><h3 class="font-black">Recent Payments</h3>@if(auth()->user()->hasPermission('reports.payments'))<a class="text-sm font-bold text-gold-600" href="{{ route('admin.reports.payments') }}">View report</a>@endif</div><div class="divide-y">@forelse($recentPayments as $payment)<div class="flex justify-between gap-3 p-4 text-sm"><span><strong class="block">{{ $payment->customer?->name ?: 'Customer' }}</strong><small class="text-neutral-500">{{ $payment->payment_code }}</small></span><strong>₹{{ number_format((float)$payment->amount,2) }}</strong></div>@empty<p class="p-5 text-sm text-neutral-500">No completed payments yet.</p>@endforelse</div></section><section class="card p-5"><h3 class="font-black">Operational Attention</h3><div class="mt-3 space-y-3 text-sm"><div class="flex justify-between"><span>Pending verification</span><strong>{{ $pendingVerification }}</strong></div><div class="flex justify-between"><span>Pending replacements</span><strong>{{ $pendingReplacements }}</strong></div><div class="flex justify-between"><span>Outstanding invoices</span><strong>{{ $pendingInvoices }}</strong></div></div></section></div>
@endsection
