<?php
namespace App\Http\Controllers\Admin;
use App\Enums\AgreementStatus;use App\Http\Controllers\Controller;use App\Http\Requests\GenerateAgreementRequest;use App\Http\Requests\StoreAgreementRequest;use App\Http\Requests\StoreAgreementSignatureRequest;use App\Http\Requests\UpdateAgreementRequest;use App\Http\Requests\UpdateAgreementStatusRequest;use App\Models\Agreement;use App\Models\AgreementTemplate;use App\Models\Assignment;use App\Models\Customer;use App\Models\CustomerRequirement;use App\Models\DocumentShareLink;use App\Models\Service;use App\Models\Worker;use App\Services\ActivityLogger;use App\Services\AgreementPdfService;use App\Services\AgreementService;use Illuminate\Http\RedirectResponse;use Illuminate\Http\Request;use Illuminate\Support\Facades\Storage;use Illuminate\Support\Str;use Illuminate\View\View;
class AgreementController extends Controller
{
 public function index(Request $request):View{$items=Agreement::with(['customer','worker','service','assignment'])->when($request->filled('search'),function($q)use($request){$t='%'.$request->string('search')->trim().'%';$q->where(fn($x)=>$x->where('agreement_code','like',$t)->orWhereHas('customer',fn($c)=>$c->where('name','like',$t)->orWhere('mobile_number','like',$t))->orWhereHas('worker',fn($w)=>$w->where('name','like',$t))->orWhereHas('assignment',fn($a)=>$a->where('assignment_code','like',$t)));})->when($request->filled('status'),fn($q)=>$q->where('status',$request->input('status')))->when($request->filled('service'),fn($q)=>$q->where('service_id',$request->integer('service')))->when($request->filled('customer'),fn($q)=>$q->where('customer_id',$request->integer('customer')))->when($request->filled('worker'),fn($q)=>$q->where('worker_id',$request->integer('worker')))->when($request->filled('date'),fn($q)=>$q->whereDate('agreement_date',$request->input('date')))->latest()->paginate(20)->withQueryString();return view('admin.agreements.index',['agreements'=>$items,'statuses'=>AgreementStatus::cases(),'services'=>Service::where('is_active',true)->get(),'customers'=>Customer::orderBy('name')->get(['id','name']),'workers'=>Worker::orderBy('name')->get(['id','name'])]);}
 public function create(Request $request,?Assignment $assignment=null):View{if($assignment?->exists)$assignment->load(['customer','worker','service','dutyType','requirement.workingCondition','requirement.householdDetail']);elseif($request->filled('assignment'))$assignment=Assignment::with(['customer','worker','service','dutyType','requirement.workingCondition','requirement.householdDetail'])->findOrFail($request->integer('assignment'));return view('admin.agreements.form',$this->formData(new Agreement,$assignment));}
 public function store(StoreAgreementRequest $request,AgreementService $service,ActivityLogger $logger):RedirectResponse{$a=$service->create($request->validated(),$request->user()->id);$logger->log('created','agreements',$a,'Agreement created.',['agreement_code'=>$a->agreement_code]);return redirect()->route('admin.agreements.show',$a)->with('success','Agreement draft created.');}
 public function show(Agreement $agreement):View{$agreement->load(['customer','worker','service','dutyType','assignment','requirement','statusHistory.changedBy','versions','invoices']);return view('admin.agreements.show',compact('agreement'));}
 public function edit(Agreement $agreement):View{abort_if($agreement->status->isReadOnly(),403,'This agreement is read-only.');$agreement->load(['assignment','customer','worker','requirement']);return view('admin.agreements.form',$this->formData($agreement,$agreement->assignment));}
 public function update(UpdateAgreementRequest $request,Agreement $agreement,AgreementService $service,ActivityLogger $logger):RedirectResponse{$oldTerms=$agreement->terms_snapshot;$service->update($agreement,$request->validated(),$request->user()->id);$logger->log('updated','agreements',$agreement,'Agreement updated.');if($oldTerms!==$request->validated('terms_snapshot'))$logger->log('terms_changed','agreements',$agreement,'Agreement terms changed.');return redirect()->route('admin.agreements.show',$agreement)->with('success','Agreement updated. Regenerate the PDF if one already exists.');}
 public function preview(Agreement $agreement):View{$agreement->load(['service','dutyType','worker.verification']);return view('admin.agreements.preview',$this->documentData($agreement,false));}
 public function print(Agreement $agreement):View{$agreement->load(['service','dutyType','worker.verification']);return view('admin.agreements.preview',$this->documentData($agreement,true));}
 public function generate(GenerateAgreementRequest $request,Agreement $agreement,AgreementPdfService $pdf,ActivityLogger $logger):RedirectResponse{$regenerated=$agreement->pdf_version>0;$pdf->generate($agreement,$request->user()->id);$logger->log($regenerated?'pdf_regenerated':'pdf_generated','agreements',$agreement,$regenerated?'Agreement PDF regenerated.':'Agreement PDF generated.');return back()->with('success',$regenerated?'PDF regenerated as a new version.':'PDF generated.');}
 public function download(Request $request,Agreement $agreement):mixed{abort_unless($request->user()->hasPermission('agreements.download'),403);abort_unless($agreement->pdf_path&&Storage::disk('local')->exists($agreement->pdf_path),404);return Storage::disk('local')->download($agreement->pdf_path,$agreement->agreement_code.'.pdf',['Content-Type'=>'application/pdf']);}
 public function customerSignature(StoreAgreementSignatureRequest $request,Agreement $agreement,AgreementService $service,ActivityLogger $logger):RedirectResponse{$service->storeSignature($agreement,'customer',$request->validated(),$request->user()->id);$logger->log('customer_signature_added','agreements',$agreement,'Customer signature added.');return back()->with('success','Customer signature saved.');}
 public function agencySignature(StoreAgreementSignatureRequest $request,Agreement $agreement,AgreementService $service,ActivityLogger $logger):RedirectResponse{$service->storeSignature($agreement,'agency',$request->validated(),$request->user()->id);$logger->log('agency_signature_added','agreements',$agreement,'Agency signature or stamp added.');return back()->with('success','Agency signature details saved.');}
 public function status(UpdateAgreementStatusRequest $request,Agreement $agreement,AgreementService $service,ActivityLogger $logger):RedirectResponse{$old=$agreement->status->value;$to=AgreementStatus::from($request->validated('status'));$service->transition($agreement,$to,$request->user()->id,$request->validated('reason'));$logger->log($to===AgreementStatus::Cancelled?'cancelled':'status_changed','agreements',$agreement,'Agreement status changed.',['from'=>$old,'to'=>$to->value]);return back()->with('success','Agreement status updated.');}
 public function whatsapp(Request $request,Agreement $agreement,AgreementService $service,ActivityLogger $logger):RedirectResponse{abort_unless($request->user()->hasPermission('agreements.share'),403);abort_unless($agreement->pdf_path,422,'Generate the PDF before sharing.');$link=DocumentShareLink::create(['token'=>Str::random(64),'document_type'=>'agreement','document_id'=>$agreement->id,'expires_at'=>now()->addDays(7),'is_active'=>true,'created_by'=>$request->user()->id]);if($agreement->status===AgreementStatus::Generated)$service->transition($agreement,AgreementStatus::Sent,$request->user()->id,'Shared through WhatsApp link');$url=route('shared.agreements.download',$link->token);$message="Hello {$agreement->customer_name_snapshot},\n\nYour Helper Home service agreement {$agreement->agreement_code} is ready.\n\nDownload: {$url}\n\nThank you,\nHelper Home";$phone=preg_replace('/\D+/','',$agreement->customer_mobile_snapshot);$logger->log('shared','agreements',$agreement,'Agreement shared through an expiring link.');return redirect()->away('https://wa.me/'.$phone.'?text='.rawurlencode($message));}
 private function documentData(Agreement $agreement,bool $printMode):array{return ['agreement'=>$agreement,'printMode'=>$printMode,'logoData'=>$this->dataUri($agreement->agency_logo_path),'customerSignature'=>$this->dataUri($agreement->customer_signature_path),'agencySignature'=>$this->dataUri($agreement->agency_signature_path),'agencyStamp'=>$this->dataUri($agreement->agency_stamp_path)];}private function dataUri(?string $path):?string{if(!$path||!Storage::disk('local')->exists($path))return null;$mime=Storage::disk('local')->mimeType($path)?:'image/png';return 'data:'.$mime.';base64,'.base64_encode(Storage::disk('local')->get($path));}
 private function formData(Agreement $agreement,?Assignment $assignment):array{$template=AgreementTemplate::where('is_default',true)->where('is_active',true)->first()??AgreementTemplate::where('is_active',true)->first();return ['agreement'=>$agreement,'selectedAssignment'=>$assignment,'assignments'=>Assignment::with(['customer:id,name','worker:id,name'])->whereIn('status',['confirmed','active','completed'])->latest()->get(),'customers'=>Customer::orderBy('name')->get(),'requirements'=>CustomerRequirement::with('service')->latest()->get(),'template'=>$template];}
}
