<?php
namespace App\Http\Controllers\Admin;
use App\Enums\PaymentMode; use App\Enums\PaymentRecordStatus; use App\Http\Controllers\Controller; use App\Http\Requests\CancelPaymentRequest; use App\Http\Requests\CompletePaymentRequest; use App\Http\Requests\StorePaymentRequest; use App\Models\Customer; use App\Models\Invoice; use App\Models\Payment; use App\Services\ActivityLogger; use App\Services\PaymentService; use Illuminate\Http\RedirectResponse; use Illuminate\Http\Request; use Illuminate\View\View;
class PaymentController extends Controller {
 public function index(Request $request):View{$q=Payment::with(['invoice','customer','receiver']);if($request->filled('search')){$t='%'.trim($request->input('search')).'%';$q->where(fn($x)=>$x->where('payment_code','like',$t)->orWhere('transaction_reference','like',$t)->orWhere('upi_reference','like',$t)->orWhereHas('invoice',fn($i)=>$i->where('invoice_number','like',$t))->orWhereHas('customer',fn($c)=>$c->where('name','like',$t)->orWhere('mobile_number','like',$t)));}foreach(['payment_mode','status','customer_id','received_by'] as $f)if($request->filled($f))$q->where($f,$request->input($f));if($request->filled('from'))$q->whereDate('payment_date','>=',$request->input('from'));if($request->filled('to'))$q->whereDate('payment_date','<=',$request->input('to'));return view('admin.payments.index',['payments'=>$q->latest('payment_date')->paginate(20)->withQueryString(),'customers'=>Customer::orderBy('name')->get(['id','name']),'modes'=>PaymentMode::cases(),'statuses'=>PaymentRecordStatus::cases()]);}
 public function create(Invoice $invoice):View{abort_if($invoice->status->value==='cancelled',422,'Cancelled invoices cannot accept payments.');return view('admin.payments.form',['invoice'=>$invoice,'modes'=>PaymentMode::cases()]);}
 public function store(StorePaymentRequest $request,Invoice $invoice,PaymentService $service,ActivityLogger $logger):RedirectResponse{$payment=$service->createPayment($invoice,$request->validated(),$request->user()->id);$logger->log('created','payments',$payment,'Payment recorded.',['payment_code'=>$payment->payment_code]);if($payment->status===PaymentRecordStatus::Completed){$logger->log('completed','payments',$payment,'Payment completed.');$logger->log('reconciled','invoices',$payment->invoice,'Invoice payment status reconciled.');}$message=$payment->status===PaymentRecordStatus::Completed?'Payment recorded and receipt created.':'Payment recorded as '.$payment->status->label().'.';return redirect()->route('admin.payments.show',$payment)->with('success',$message);}
 public function show(Payment $payment):View{$payment->load(['invoice','customer','receiver','receipt','statusHistory.changedBy']);return view('admin.payments.show',compact('payment'));}
 public function complete(CompletePaymentRequest $request,Payment $payment,PaymentService $service,ActivityLogger $logger):RedirectResponse{$payment=$service->completePayment($payment,$request->user()->id,$request->validated('reason'));$logger->log('completed','payments',$payment,'Payment completed.');$logger->log('reconciled','invoices',$payment->invoice,'Invoice payment status reconciled.');return back()->with('success','Payment completed and receipt created.');}
 public function cancel(CancelPaymentRequest $request,Payment $payment,PaymentService $service,ActivityLogger $logger):RedirectResponse{$payment=$service->cancelPayment($payment,$request->user()->id,$request->validated('reason'));$logger->log('cancelled','payments',$payment,'Payment cancelled.');$logger->log('reconciled','invoices',$payment->invoice,'Invoice payment status reconciled after cancellation.');return back()->with('success','Payment cancelled and invoice reconciled.');}
}
