<?php
namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller; use App\Http\Requests\GeneratePaymentReceiptRequest; use App\Models\Customer; use App\Models\PaymentReceipt; use App\Services\ActivityLogger; use App\Services\PaymentReceiptPdfService; use Illuminate\Http\RedirectResponse; use Illuminate\Http\Request; use Illuminate\Support\Facades\Storage; use Illuminate\Support\Str; use Illuminate\View\View; use App\Models\DocumentShareLink;
class PaymentReceiptController extends Controller {
 public function index(Request $request):View{$q=PaymentReceipt::with(['payment','invoice','customer']);if($request->filled('search')){$t='%'.trim($request->input('search')).'%';$q->where(fn($x)=>$x->where('receipt_number','like',$t)->orWhereHas('invoice',fn($i)=>$i->where('invoice_number','like',$t))->orWhereHas('customer',fn($c)=>$c->where('name','like',$t)->orWhere('mobile_number','like',$t)));}if($request->filled('customer_id'))$q->where('customer_id',$request->input('customer_id'));if($request->filled('date'))$q->whereDate('receipt_date',$request->input('date'));return view('admin.payment-receipts.index',['receipts'=>$q->latest('receipt_date')->paginate(20)->withQueryString(),'customers'=>Customer::orderBy('name')->get(['id','name'])]);}
 public function show(PaymentReceipt $receipt):View{$receipt->load(['payment','invoice','customer']);return view('admin.payment-receipts.show',compact('receipt'));}
 public function preview(PaymentReceipt $receipt,PaymentReceiptPdfService $pdf):View{$receipt->load(['payment','invoice']);return view('admin.payment-receipts.preview',$pdf->data($receipt));}
 public function print(PaymentReceipt $receipt,PaymentReceiptPdfService $pdf):View{return $this->preview($receipt,$pdf);}
 public function generate(GeneratePaymentReceiptRequest $request,PaymentReceipt $receipt,PaymentReceiptPdfService $pdf,ActivityLogger $logger):RedirectResponse{if($receipt->pdf_version&&!$request->boolean('confirm_regenerate'))return back()->withErrors(['confirm_regenerate'=>'Confirm receipt PDF regeneration.']);$receipt=$pdf->generate($receipt,$request->user()->id);$logger->log('generated','payment-receipts',$receipt,'Payment receipt PDF generated.');return back()->with('success','Receipt PDF generated.');}
 public function download(PaymentReceipt $receipt):mixed{abort_unless($receipt->pdf_path&&Storage::disk('local')->exists($receipt->pdf_path),404);return Storage::disk('local')->download($receipt->pdf_path,$receipt->receipt_number.'.pdf',['Content-Type'=>'application/pdf']);}
 public function whatsapp(Request $request,PaymentReceipt $receipt,ActivityLogger $logger):RedirectResponse{abort_unless($receipt->pdf_path,422,'Generate the receipt PDF first.');$link=DocumentShareLink::create(['token'=>Str::random(64),'document_type'=>'payment_receipt','document_id'=>$receipt->id,'expires_at'=>now()->addDays(7),'is_active'=>true,'created_by'=>$request->user()->id]);$url=route('shared.payment-receipts.download',$link->token);$message="Hello {$receipt->customer_name_snapshot},\n\nThank you for your payment to Helper Home.\n\nReceipt: {$receipt->receipt_number}\nInvoice: {$receipt->invoice->invoice_number}\nAmount Received: ₹{$receipt->payment_amount_snapshot}\nBalance Due: ₹{$receipt->balance_amount_snapshot}\n\nDownload Receipt: {$url}\n\nThank you,\nHelper Home";$phone=preg_replace('/\D+/','',(string)$receipt->customer_mobile_snapshot);$logger->log('shared','payment-receipts',$receipt,'Payment receipt shared through expiring link.');return redirect()->away('https://wa.me/'.$phone.'?text='.rawurlencode($message));}
}
