<?php
namespace App\Models;
use App\Enums\InvoiceStatus;use App\Enums\PaymentStatus;use Illuminate\Database\Eloquent\Attributes\Fillable;use Illuminate\Database\Eloquent\Model;use Illuminate\Database\Eloquent\Relations\BelongsTo;use Illuminate\Database\Eloquent\Relations\HasMany;
#[Fillable(['invoice_number','customer_id','customer_requirement_id','assignment_id','agreement_id','invoice_date','due_date','billing_period_start','billing_period_end','subtotal','discount_type','discount_value','discount_amount','tax_type','tax_rate','cgst_rate','cgst_amount','sgst_rate','sgst_amount','igst_rate','igst_amount','tax_total','round_off','total_amount','paid_amount','balance_amount','payment_status','status','notes','terms','agency_name_snapshot','agency_address_snapshot','agency_phone_snapshot','agency_email_snapshot','agency_gst_snapshot','agency_logo_snapshot','bank_holder_snapshot','bank_name_snapshot','bank_account_snapshot','bank_ifsc_snapshot','bank_branch_snapshot','upi_id_snapshot','upi_qr_snapshot','customer_name_snapshot','customer_address_snapshot','customer_mobile_snapshot','customer_email_snapshot','customer_gst_snapshot','signature_path_snapshot','stamp_path_snapshot','pdf_path','pdf_generated_at','pdf_version','created_by','updated_by'])]
class Invoice extends Model
{
 protected static function booted():void{static::updating(fn(self $m)=>$m->isDirty('invoice_number')?$m->invoice_number=$m->getOriginal('invoice_number'):null);}
 public function customer():BelongsTo{return $this->belongsTo(Customer::class);}public function requirement():BelongsTo{return $this->belongsTo(CustomerRequirement::class,'customer_requirement_id');}public function assignment():BelongsTo{return $this->belongsTo(Assignment::class);}public function agreement():BelongsTo{return $this->belongsTo(Agreement::class);}public function items():HasMany{return $this->hasMany(InvoiceItem::class)->orderBy('sort_order');}public function statusHistory():HasMany{return $this->hasMany(InvoiceStatusHistory::class);}public function paymentStatusHistory():HasMany{return $this->hasMany(InvoicePaymentStatusHistory::class);}public function versions():HasMany{return $this->hasMany(InvoiceVersion::class);}public function payments():HasMany{return $this->hasMany(Payment::class);}public function receipts():HasMany{return $this->hasMany(PaymentReceipt::class);}
 public function effectivePaymentStatus():PaymentStatus{if($this->status!==InvoiceStatus::Cancelled&&$this->payment_status!==PaymentStatus::Paid&&$this->due_date?->isBefore(today())&&bccomp((string)$this->balance_amount,'0',2)>0)return PaymentStatus::Overdue;return $this->payment_status;}
 protected function casts():array{return ['invoice_date'=>'date','due_date'=>'date','billing_period_start'=>'date','billing_period_end'=>'date','pdf_generated_at'=>'datetime','status'=>InvoiceStatus::class,'payment_status'=>PaymentStatus::class,'subtotal'=>'decimal:2','discount_value'=>'decimal:2','discount_amount'=>'decimal:2','tax_rate'=>'decimal:2','cgst_rate'=>'decimal:2','cgst_amount'=>'decimal:2','sgst_rate'=>'decimal:2','sgst_amount'=>'decimal:2','igst_rate'=>'decimal:2','igst_amount'=>'decimal:2','tax_total'=>'decimal:2','round_off'=>'decimal:2','total_amount'=>'decimal:2','paid_amount'=>'decimal:2','balance_amount'=>'decimal:2'];}
}
