@extends('layouts.admin')
@section('title',$worker->exists?'Edit Worker':'Register Worker') @section('heading',$worker->exists?'Edit Worker':'Register Worker') @section('subheading','Complete each section. At least one service and five references are required.')
@section('content')
@php
$refs=old('references',$worker->exists?$worker->references->map(fn($r)=>$r->only(['name','mobile_number','relation','occupation','address','notes']))->all():[]);
while(count($refs)<5)$refs[]=['name'=>'','mobile_number'=>'','relation'=>'','occupation'=>'','address'=>'','notes'=>''];
$selectedServices=old('services',$worker->exists?$worker->services->pluck('id')->all():[]);
@endphp
<form method="POST" enctype="multipart/form-data" action="{{ $worker->exists?route('admin.workers.update',$worker):route('admin.workers.store') }}">@csrf @if($worker->exists)@method('PUT')@endif
<div class="card mb-6 overflow-x-auto p-2"><div class="flex min-w-max gap-1">@foreach(['personal'=>'1. Personal Details','work'=>'2. Work & Services','documents'=>'3. Documents','references'=>'4. References','internal'=>'5. Internal Details'] as $tab=>$label)<button type="button" data-tab-button="{{ $tab }}" class="rounded-xl px-4 py-2.5 text-sm font-bold text-neutral-500 first:bg-charcoal-900 first:text-white">{{ $label }}</button>@endforeach</div></div>

<section data-tab-panel="personal" class="card p-6 md:p-8"><h2 class="mb-5 text-lg font-black">Personal Details</h2><div class="grid gap-5 md:grid-cols-2 lg:grid-cols-3">
<div><label>Worker Code</label><input value="{{ $worker->worker_code ?: 'Generated after save' }}" readonly></div><div><label>Registration Date</label><input type="date" name="registration_date" value="{{ old('registration_date',$worker->registration_date?->format('Y-m-d')??today()->format('Y-m-d')) }}" required></div><div><label>Registration Number</label><input name="registration_number" value="{{ old('registration_number',$worker->registration_number) }}"></div>
<div><label>Worker Name</label><input name="name" value="{{ old('name',$worker->name) }}" required></div><div><label>Worker Photo</label><input type="file" name="photo" accept="image/jpeg,image/png,image/webp"></div><div><label>Mobile Number</label><input name="mobile_number" value="{{ old('mobile_number',$worker->mobile_number) }}" required></div>
<div><label>Alternate Mobile</label><input name="alternate_mobile_number" value="{{ old('alternate_mobile_number',$worker->alternate_mobile_number) }}"></div><div><label>Email</label><input type="email" name="email" value="{{ old('email',$worker->email) }}"></div><div><label>Date of Joining</label><input type="date" name="date_of_joining" value="{{ old('date_of_joining',$worker->date_of_joining?->format('Y-m-d')) }}"></div>
<div class="lg:col-span-2"><label>Address Line 1</label><input name="address_line_1" value="{{ old('address_line_1',$worker->address_line_1) }}" required></div><div><label>Address Line 2</label><input name="address_line_2" value="{{ old('address_line_2',$worker->address_line_2) }}"></div><div><label>City</label><input name="city" value="{{ old('city',$worker->city) }}" required></div><div><label>State</label><input name="state" value="{{ old('state',$worker->state) }}" required></div><div><label>Pincode</label><input name="pincode" value="{{ old('pincode',$worker->pincode) }}"></div><div><label>Country</label><input name="country" value="{{ old('country',$worker->country?:'India') }}" required></div>
<div><label>Date of Birth</label><input id="date_of_birth" type="date" name="date_of_birth" value="{{ old('date_of_birth',$worker->date_of_birth?->format('Y-m-d')) }}"></div><div><label>Age</label><input id="age" type="number" min="0" max="120" name="age" value="{{ old('age',$worker->age) }}"></div><div><label>Gender</label><select name="gender"><option value="">Select</option>@foreach(['male','female','other','prefer_not_to_say'] as $value)<option value="{{ $value }}" @selected(old('gender',$worker->gender)===$value)>{{ str($value)->headline() }}</option>@endforeach</select></div><div><label>Marital Status</label><select name="marital_status"><option value="">Select</option>@foreach(['single','married','widowed','divorced','other'] as $value)<option value="{{ $value }}" @selected(old('marital_status',$worker->marital_status)===$value)>{{ str($value)->headline() }}</option>@endforeach</select></div><div class="md:col-span-2"><label>Concerned Police Station</label><input name="police_station_name" value="{{ old('police_station_name',$worker->police_station_name) }}"></div></div></section>

<section data-tab-panel="work" class="card hidden p-6 md:p-8"><h2 class="mb-5 text-lg font-black">Work & Service Details</h2><div class="mb-6"><label>Service Categories</label><div class="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">@foreach($services as $service)<label class="flex items-center gap-3 rounded-xl border p-3 font-normal"><input class="h-4 w-4" type="checkbox" name="services[]" value="{{ $service->id }}" @checked(in_array($service->id,$selectedServices))>{{ $service->name }}</label>@endforeach</div></div><div class="grid gap-5 md:grid-cols-2"><div><label>Years of Experience</label><input type="number" step="0.5" min="0" name="years_of_experience" value="{{ old('years_of_experience',$worker->years_of_experience) }}"></div><div><label>Salary Expectation</label><input type="number" step="0.01" min="0" name="salary_expectation" value="{{ old('salary_expectation',$worker->salary_expectation) }}"></div><div><label>Preferred Duty Type</label><select name="preferred_duty_type_id"><option value="">Select</option>@foreach($dutyTypes as $type)<option value="{{ $type->id }}" @selected(old('preferred_duty_type_id',$worker->preferred_duty_type_id)==$type->id)>{{ $type->name }}</option>@endforeach</select></div><div><label>Preferred Work Location</label><input name="preferred_work_location" value="{{ old('preferred_work_location',$worker->preferred_work_location) }}"></div><div><label>Availability</label><select name="availability_status" required>@foreach($availabilityStatuses as $status)<option value="{{ $status->value }}" @selected(old('availability_status',$worker->availability_status?->value??'available')===$status->value)>{{ str($status->value)->headline() }}</option>@endforeach</select></div><div><label>Worker Status</label><select name="worker_status" required>@foreach($workerStatuses as $status)<option value="{{ $status->value }}" @selected(old('worker_status',$worker->worker_status?->value??'active')===$status->value)>{{ str($status->value)->headline() }}</option>@endforeach</select></div><div class="md:col-span-2"><label>Experience / Skills Notes</label><textarea name="experience_notes" rows="5">{{ old('experience_notes',$worker->experience_notes) }}</textarea></div></div></section>

<section data-tab-panel="documents" class="card hidden p-6 md:p-8"><div class="mb-5 flex items-center justify-between"><div><h2 class="text-lg font-black">Documents</h2><p class="text-sm text-neutral-500">PDF or image, maximum 5 MB.</p></div><button type="button" id="addDocument" class="btn-secondary">+ Add Document</button></div>@if($worker->exists)<p class="mb-4 rounded-xl bg-neutral-50 p-3 text-sm">Existing documents remain unchanged here. Manage them from the worker detail page.</p>@endif<div id="documentRows" class="space-y-4"></div></section>

<section data-tab-panel="references" class="card hidden p-6 md:p-8"><div class="mb-5 flex items-center justify-between"><div><h2 class="text-lg font-black">References</h2><p class="text-sm text-neutral-500">Five complete references are required; additional references are supported.</p></div><button type="button" id="addReference" class="btn-secondary">+ Add Reference</button></div><div id="referenceRows" class="space-y-4">@foreach($refs as $i=>$ref)<div class="reference-row rounded-2xl border border-neutral-200 p-4"><div class="mb-3 flex justify-between"><strong>Reference <span class="reference-number">{{ $i+1 }}</span></strong><button type="button" class="remove-reference text-sm font-bold text-red-600">Remove</button></div><div class="grid gap-3 md:grid-cols-3"><input name="references[{{ $i }}][name]" value="{{ $ref['name']??'' }}" placeholder="Name" required><input name="references[{{ $i }}][mobile_number]" value="{{ $ref['mobile_number']??'' }}" placeholder="Mobile" required><input name="references[{{ $i }}][relation]" value="{{ $ref['relation']??'' }}" placeholder="Relation" required><input name="references[{{ $i }}][occupation]" value="{{ $ref['occupation']??'' }}" placeholder="Occupation"><input name="references[{{ $i }}][address]" value="{{ $ref['address']??'' }}" placeholder="Address"><input name="references[{{ $i }}][notes]" value="{{ $ref['notes']??'' }}" placeholder="Notes"></div></div>@endforeach</div></section>

<section data-tab-panel="internal" class="card hidden p-6 md:p-8"><h2 class="mb-5 text-lg font-black">Internal Details</h2><div class="grid gap-5 md:grid-cols-2"><div><label>Supervisor</label><select name="supervisor_user_id"><option value="">Select</option>@foreach($eligibleUsers as $user)<option value="{{ $user->id }}" @selected(old('supervisor_user_id',$worker->supervisor_user_id)==$user->id)>{{ $user->name }}</option>@endforeach</select></div><div><label>Executive</label><select name="executive_user_id"><option value="">Select</option>@foreach($eligibleUsers as $user)<option value="{{ $user->id }}" @selected(old('executive_user_id',$worker->executive_user_id)==$user->id)>{{ $user->name }}</option>@endforeach</select></div><div><label>Registration Source</label><select name="registration_source"><option value="">Select</option>@foreach(['admin','staff','walk_in','website','other'] as $source)<option value="{{ $source }}" @selected(old('registration_source',$worker->registration_source)===$source)>{{ str($source)->headline() }}</option>@endforeach</select></div><div class="md:col-span-2"><label>Internal Notes</label><textarea name="notes" rows="5">{{ old('notes',$worker->notes) }}</textarea></div></div></section>
<div class="mt-6 flex gap-3"><button class="btn-primary" type="submit">{{ $worker->exists?'Update worker':'Complete registration' }}</button><a class="btn-secondary" href="{{ route('admin.workers.index') }}">Cancel</a></div></form>

<template id="referenceTemplate"><div class="reference-row rounded-2xl border border-neutral-200 p-4"><div class="mb-3 flex justify-between"><strong>Reference <span class="reference-number"></span></strong><button type="button" class="remove-reference text-sm font-bold text-red-600">Remove</button></div><div class="grid gap-3 md:grid-cols-3"><input data-field="name" placeholder="Name" required><input data-field="mobile_number" placeholder="Mobile" required><input data-field="relation" placeholder="Relation" required><input data-field="occupation" placeholder="Occupation"><input data-field="address" placeholder="Address"><input data-field="notes" placeholder="Notes"></div></div></template>
<template id="documentTemplate"><div class="document-row rounded-2xl border border-neutral-200 p-4"><div class="mb-3 flex justify-between"><strong>New Document</strong><button type="button" class="remove-document text-sm font-bold text-red-600">Remove</button></div><div class="grid gap-3 md:grid-cols-3"><select data-field="document_type" required><option value="">Document type</option>@foreach(['identity_proof','address_proof','police_verification','background_verification','certificate','other'] as $type)<option value="{{ $type }}">{{ str($type)->headline() }}</option>@endforeach</select><input data-field="document_name" placeholder="Document name"><input data-field="document_number" placeholder="Document number"><input data-field="file" type="file" accept=".pdf,image/jpeg,image/png,image/webp" required><input data-field="issue_date" type="date"><input data-field="expiry_date" type="date"><input class="md:col-span-3" data-field="remarks" placeholder="Remarks"></div></div></template>
<script>
document.querySelectorAll('[data-tab-button]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-tab-button]').forEach(x=>x.className='rounded-xl px-4 py-2.5 text-sm font-bold text-neutral-500');b.className='rounded-xl bg-charcoal-900 px-4 py-2.5 text-sm font-bold text-white';document.querySelectorAll('[data-tab-panel]').forEach(p=>p.classList.toggle('hidden',p.dataset.tabPanel!==b.dataset.tabButton))}));
const renumberRefs=()=>document.querySelectorAll('.reference-row').forEach((row,i)=>{row.querySelector('.reference-number').textContent=i+1;row.querySelectorAll('[data-field]').forEach(x=>x.name=`references[${i}][${x.dataset.field}]`)});
document.getElementById('addReference').onclick=()=>{document.getElementById('referenceRows').append(document.getElementById('referenceTemplate').content.cloneNode(true));renumberRefs()};
document.addEventListener('click',e=>{if(e.target.matches('.remove-reference')){if(document.querySelectorAll('.reference-row').length>5)e.target.closest('.reference-row').remove();renumberRefs()}if(e.target.matches('.remove-document'))e.target.closest('.document-row').remove()});
let docIndex=0;document.getElementById('addDocument').onclick=()=>{const node=document.getElementById('documentTemplate').content.cloneNode(true);node.querySelectorAll('[data-field]').forEach(x=>x.name=`documents[${docIndex}][${x.dataset.field}]`);docIndex++;document.getElementById('documentRows').append(node)};
document.getElementById('date_of_birth').addEventListener('change',e=>{if(!e.target.value)return;const d=new Date(e.target.value),n=new Date();let a=n.getFullYear()-d.getFullYear();if(n<new Date(n.getFullYear(),d.getMonth(),d.getDate()))a--;document.getElementById('age').value=Math.max(0,a)});
</script>
@endsection
