@extends('layouts.admin')
@section('title','Workers') @section('heading','Workers') @section('subheading','Search, filter, and manage registered workers.')
@section('actions') @if(auth()->user()->hasPermission('workers.create'))<a href="{{ route('admin.workers.create') }}" class="btn-primary">+ Add worker</a>@endif @endsection
@section('content')
<form method="GET" class="card mb-6 grid gap-3 p-4 md:grid-cols-4 xl:grid-cols-8">
    <input class="md:col-span-2" name="search" value="{{ request('search') }}" placeholder="Code, name, mobile or city">
    <select name="service"><option value="">All services</option>@foreach($services as $service)<option value="{{ $service->id }}" @selected(request('service')==$service->id)>{{ $service->name }}</option>@endforeach</select>
    <select name="availability"><option value="">All availability</option>@foreach($availabilityStatuses as $status)<option value="{{ $status->value }}" @selected(request('availability')===$status->value)>{{ str($status->value)->headline() }}</option>@endforeach</select>
    <select name="status"><option value="">All statuses</option>@foreach($workerStatuses as $status)<option value="{{ $status->value }}" @selected(request('status')===$status->value)>{{ str($status->value)->headline() }}</option>@endforeach</select>
    <select name="verification"><option value="">All verification</option>@foreach($verificationStatuses as $status)<option value="{{ $status->value }}" @selected(request('verification')===$status->value)>{{ str($status->value)->headline() }}</option>@endforeach</select>
    <select name="gender"><option value="">All genders</option>@foreach(['male','female','other','prefer_not_to_say'] as $gender)<option value="{{ $gender }}" @selected(request('gender')===$gender)>{{ str($gender)->headline() }}</option>@endforeach</select>
    <button class="btn-primary" type="submit">Filter</button>
</form>
<div class="card overflow-hidden"><div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead class="border-b bg-neutral-50 text-xs uppercase tracking-wider text-neutral-500"><tr><th class="px-4 py-4">Worker</th><th class="px-4 py-4">Mobile</th><th class="px-4 py-4">Primary service</th><th class="px-4 py-4">City</th><th class="px-4 py-4">Experience</th><th class="px-4 py-4">Availability</th><th class="px-4 py-4">Verification</th><th class="px-4 py-4">Status</th><th class="px-4 py-4">Supervisor</th><th class="px-4 py-4"></th></tr></thead><tbody class="divide-y divide-neutral-100">
@forelse($workers as $worker)<tr class="hover:bg-neutral-50"><td class="px-4 py-4"><div class="flex items-center gap-3">@if($worker->photo_path)<img class="h-10 w-10 rounded-xl object-cover" src="{{ Storage::url($worker->photo_path) }}" alt="">@else<span class="grid h-10 w-10 place-items-center rounded-xl bg-neutral-200 font-bold">{{ str($worker->name)->substr(0,1) }}</span>@endif<div><a class="font-bold text-neutral-900 hover:text-gold-500" href="{{ route('admin.workers.show',$worker) }}">{{ $worker->name }}</a><p class="font-mono text-xs text-neutral-400">{{ $worker->worker_code }}</p></div></div></td><td class="px-4 py-4">{{ $worker->mobile_number }}</td><td class="px-4 py-4">{{ $worker->services->first()?->name ?? '—' }}</td><td class="px-4 py-4">{{ $worker->city }}</td><td class="px-4 py-4">{{ $worker->years_of_experience !== null ? $worker->years_of_experience.' yrs' : '—' }}</td><td class="px-4 py-4"><span class="badge-active">{{ str($worker->availability_status->value)->headline() }}</span></td><td class="px-4 py-4"><span class="{{ $worker->verification?->overall_verification_status?->value==='verified'?'badge-active':'badge-inactive' }}">{{ str($worker->verification?->overall_verification_status?->value ?? 'pending')->headline() }}</span></td><td class="px-4 py-4"><span class="{{ $worker->worker_status->value==='active'?'badge-active':'badge-inactive' }}">{{ str($worker->worker_status->value)->headline() }}</span></td><td class="px-4 py-4">{{ $worker->supervisor?->name ?? '—' }}</td><td class="px-4 py-4"><a class="font-bold text-gold-500" href="{{ route('admin.workers.show',$worker) }}">View</a></td></tr>@empty<tr><td colspan="10" class="px-6 py-12 text-center text-neutral-500">No workers match these filters.</td></tr>@endforelse
</tbody></table></div>@if($workers->hasPages())<div class="border-t px-5 py-4">{{ $workers->links() }}</div>@endif</div>
@endsection
