<!doctype html><html lang="en"><head><meta charset="utf-8"><title>{{ $invoice->invoice_number }}</title><style>
@page{size:A4;margin:18mm}body{font-family:DejaVu Sans,sans-serif;color:#252525;font-size:10px;line-height:1.5}h1,h2,p{margin:0}.top{display:table;width:100%;border-bottom:3px solid #c89835;padding-bottom:15px}.left,.right{display:table-cell;vertical-align:top}.right{text-align:right}.logo{max-width:90px;max-height:60px}.brand{font-size:23px;font-weight:bold;color:#a97718}.title{font-size:20px;color:#a97718;font-weight:bold}.muted{color:#666}.gap{margin-top:22px}.row{display:table;width:100%}.col{display:table-cell;width:50%;vertical-align:top}.details{margin-top:8px}table{width:100%;border-collapse:collapse;margin-top:20px}th{background:#f7ebd1;text-align:left}th,td{padding:8px 6px;border-bottom:1px solid #ddd}.num{text-align:right}.totals{width:42%;margin-left:auto}.totals td{padding:4px 6px}.grand{font-weight:bold;font-size:14px;border-top:2px solid #c89835}.footer{margin-top:26px;border-top:1px solid #ddd;padding-top:15px}.qr{width:90px;height:90px;object-fit:contain}.sign{max-width:110px;max-height:50px}.stamp{max-width:80px;max-height:65px}.block{page-break-inside:avoid}
</style></head><body>
<div class="top"><div class="left">@if($logoData)<img class="logo" src="{{ $logoData }}"><br>@endif<strong class="brand">{{ $invoice->agency_name_snapshot ?: 'Helper Home' }}</strong><br><span class="muted">Home Care &amp; Domestic Services</span><div class="details">{{ $invoice->agency_address_snapshot }}<br>{{ $invoice->agency_phone_snapshot }} @if($invoice->agency_email_snapshot) · {{ $invoice->agency_email_snapshot }} @endif<br>@if($invoice->agency_gst_snapshot)GSTIN: {{ $invoice->agency_gst_snapshot }}@endif</div></div><div class="right"><div class="title">TAX INVOICE</div><div class="details"><strong>Invoice No:</strong> {{ $invoice->invoice_number }}<br><strong>Invoice Date:</strong> {{ $invoice->invoice_date->format('d M Y') }}<br>@if($invoice->due_date)<strong>Due Date:</strong> {{ $invoice->due_date->format('d M Y') }}<br>@endif @if($invoice->billing_period_start)<strong>Period:</strong> {{ $invoice->billing_period_start->format('d M Y') }} – {{ $invoice->billing_period_end?->format('d M Y') ?: 'Ongoing' }}@endif</div></div></div>
<div class="gap row"><div class="col"><strong>Bill To</strong><br>{{ $invoice->customer_name_snapshot }}<br>{{ $invoice->customer_address_snapshot }}<br>{{ $invoice->customer_mobile_snapshot }}<br>{{ $invoice->customer_email_snapshot }}<br>@if($invoice->customer_gst_snapshot)GSTIN: {{ $invoice->customer_gst_snapshot }}@endif</div><div class="col right">@if($invoice->assignment)<strong>Assignment:</strong> {{ $invoice->assignment->assignment_code }}<br>@endif @if($invoice->agreement)<strong>Agreement:</strong> {{ $invoice->agreement->agreement_code }}@endif</div></div>
<table><thead><tr><th>Sr</th><th>Description</th><th>HSN/SAC</th><th class="num">Qty</th><th class="num">Rate</th><th class="num">Amount</th></tr></thead><tbody>@foreach($invoice->items as $item)<tr><td>{{ $loop->iteration }}</td><td>{{ $item->description }} @if($item->unit)<small>({{ $item->unit }})</small>@endif</td><td>{{ $item->hsn_sac_code }}</td><td class="num">{{ $item->quantity }}</td><td class="num">₹{{ number_format((float)$item->rate,2) }}</td><td class="num">₹{{ number_format((float)$item->amount,2) }}</td></tr>@endforeach</tbody></table>
<div class="block gap"><table class="totals"><tr><td>Subtotal</td><td class="num">₹{{ number_format((float)$invoice->subtotal,2) }}</td></tr>@if((float)$invoice->discount_amount>0)<tr><td>Discount</td><td class="num">- ₹{{ number_format((float)$invoice->discount_amount,2) }}</td></tr>@endif @if($invoice->tax_type==='intra_state')<tr><td>CGST ({{ $invoice->cgst_rate }}%)</td><td class="num">₹{{ number_format((float)$invoice->cgst_amount,2) }}</td></tr><tr><td>SGST ({{ $invoice->sgst_rate }}%)</td><td class="num">₹{{ number_format((float)$invoice->sgst_amount,2) }}</td></tr>@elseif($invoice->tax_type==='inter_state')<tr><td>IGST ({{ $invoice->igst_rate }}%)</td><td class="num">₹{{ number_format((float)$invoice->igst_amount,2) }}</td></tr>@endif @if((float)$invoice->round_off!=0)<tr><td>Round Off</td><td class="num">₹{{ number_format((float)$invoice->round_off,2) }}</td></tr>@endif<tr class="grand"><td>TOTAL</td><td class="num">₹{{ number_format((float)$invoice->total_amount,2) }}</td></tr></table></div>
<div class="footer row block"><div class="col"><strong>Bank / Payment Details</strong><br>{{ $invoice->bank_holder_snapshot }}<br>{{ $invoice->bank_name_snapshot }}<br>@if($invoice->bank_account_snapshot)Account: {{ $invoice->bank_account_snapshot }}<br>@endif @if($invoice->bank_ifsc_snapshot)IFSC: {{ $invoice->bank_ifsc_snapshot }}<br>@endif @if($invoice->bank_branch_snapshot)Branch: {{ $invoice->bank_branch_snapshot }}<br>@endif @if($invoice->upi_id_snapshot)UPI: {{ $invoice->upi_id_snapshot }}@endif @if($qrData)<br><img class="qr" src="{{ $qrData }}">@endif</div><div class="col right">@if($signatureData)<img class="sign" src="{{ $signatureData }}">@endif @if($stampData)<img class="stamp" src="{{ $stampData }}">@endif<br>Authorized Sign &amp; Stamp</div></div>
@if($invoice->notes)<div class="gap block"><strong>Notes</strong><br>{!! nl2br(e($invoice->notes)) !!}</div>@endif @if($invoice->terms)<div class="gap block"><strong>Payment Terms</strong><br>{!! nl2br(e($invoice->terms)) !!}</div>@endif
</body></html>
