@extends('layouts.admin')
@section('title', $invoice->exists ? 'Edit Invoice' : 'Create Invoice')
@section('heading', $invoice->exists ? 'Edit '.$invoice->invoice_number : 'Create Invoice')
@section('subheading', 'Review and remove any source charges that do not apply before generating the PDF.')
@section('content')
<form method="POST" action="{{ $invoice->exists ? route('admin.invoices.update', $invoice) : route('admin.invoices.store') }}" class="space-y-6">
    @csrf @if($invoice->exists) @method('PUT') @endif
    @if($invoice->exists && $invoice->status !== \App\Enums\InvoiceStatus::Draft)<div class="rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm"><strong>PDF version {{ $invoice->pdf_version }} exists.</strong> Saving will generate a new version and preserve the previous PDF. <label class="mt-2 flex gap-2"><input type="checkbox" name="confirm_regenerate" value="1" required> I confirm regeneration</label></div>@endif
    <section class="card p-6"><h2 class="mb-4 text-lg font-black">1. Invoice Source</h2><div class="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
        <div><label>Customer *</label><select id="customer" name="customer_id" required><option value="">Select customer</option>@foreach($customers as $c)<option value="{{ $c->id }}" data-name="{{ $c->name }}" data-address="{{ collect([$c->address_line_1,$c->address_line_2,$c->location,$c->city,$c->state,$c->pincode,$c->country])->filter()->join(', ') }}" data-mobile="{{ $c->mobile_number }}" data-email="{{ $c->email }}" @selected(old('customer_id',$invoice->customer_id ?? $customer?->id)==$c->id)>{{ $c->name }} · {{ $c->mobile_number }}</option>@endforeach</select></div>
        <div><label>Requirement</label><select id="requirement" name="customer_requirement_id"><option value="">None</option>@foreach($requirements as $r)<option value="{{ $r->id }}" data-customer="{{ $r->customer_id }}" @selected(old('customer_requirement_id',$invoice->customer_requirement_id ?? $assignment?->customer_requirement_id ?? $agreement?->customer_requirement_id)==$r->id)>{{ $r->requirement_code }}</option>@endforeach</select></div>
        <div><label>Assignment</label><select id="assignment" name="assignment_id"><option value="">None</option>@foreach($assignments as $a)<option value="{{ $a->id }}" data-customer="{{ $a->customer_id }}" data-requirement="{{ $a->customer_requirement_id }}" data-charge="{{ $a->agency_service_charge }}" data-salary="{{ $a->monthly_salary }}" data-service="{{ $a->service_id }}" @selected(old('assignment_id',$invoice->assignment_id ?? $assignment?->id)==$a->id)>{{ $a->assignment_code }} · {{ $a->customer?->name }}</option>@endforeach</select></div>
        <div><label>Agreement</label><select id="agreement" name="agreement_id"><option value="">None</option>@foreach($agreements as $a)<option value="{{ $a->id }}" data-customer="{{ $a->customer_id }}" data-assignment="{{ $a->assignment_id }}" data-requirement="{{ $a->customer_requirement_id }}" data-charge="{{ $a->monthly_agency_service_charge }}" data-salary="{{ $a->monthly_salary }}" data-service="{{ $a->service_id }}" @selected(old('agreement_id',$invoice->agreement_id ?? $agreement?->id)==$a->id)>{{ $a->agreement_code }} · {{ $a->customer?->name }}</option>@endforeach</select></div>
        <div><label>Invoice Date *</label><input required type="date" name="invoice_date" value="{{ old('invoice_date',$invoice->invoice_date?->format('Y-m-d') ?? today()->format('Y-m-d')) }}"></div><div><label>Due Date</label><input type="date" name="due_date" value="{{ old('due_date',$invoice->due_date?->format('Y-m-d')) }}"></div><div><label>Billing Period Start</label><input type="date" name="billing_period_start" value="{{ old('billing_period_start',$invoice->billing_period_start?->format('Y-m-d') ?? $assignment?->assignment_start_date?->format('Y-m-d')) }}"></div><div><label>Billing Period End</label><input type="date" name="billing_period_end" value="{{ old('billing_period_end',$invoice->billing_period_end?->format('Y-m-d') ?? $assignment?->assignment_end_date?->format('Y-m-d')) }}"></div>
    </div></section>
    <section class="card p-6"><h2 class="mb-4 text-lg font-black">2. Customer Details</h2><p class="mb-3 text-sm text-neutral-500">These values are stored on the invoice and do not change the customer record.</p><div class="grid gap-4 md:grid-cols-2"><div><label>Name</label><input id="customerName" name="customer_name_snapshot" value="{{ old('customer_name_snapshot',$invoice->customer_name_snapshot ?? $customer?->name) }}"></div><div><label>Mobile</label><input id="customerMobile" name="customer_mobile_snapshot" value="{{ old('customer_mobile_snapshot',$invoice->customer_mobile_snapshot ?? $customer?->mobile_number) }}"></div><div><label>Email</label><input id="customerEmail" type="email" name="customer_email_snapshot" value="{{ old('customer_email_snapshot',$invoice->customer_email_snapshot ?? $customer?->email) }}"></div><div><label>GST Number</label><input name="customer_gst_snapshot" value="{{ old('customer_gst_snapshot',$invoice->customer_gst_snapshot) }}"></div><div class="md:col-span-2"><label>Address</label><textarea id="customerAddress" name="customer_address_snapshot">{{ old('customer_address_snapshot',$invoice->customer_address_snapshot ?? ($customer ? collect([$customer->address_line_1,$customer->address_line_2,$customer->location,$customer->city,$customer->state,$customer->pincode,$customer->country])->filter()->join(', ') : '')) }}</textarea></div></div></section>
    <section class="card p-6"><h2 class="mb-4 text-lg font-black">3. Invoice Items</h2><div class="max-w-full overflow-x-auto"><table class="w-full min-w-[850px] text-sm"><thead><tr><th class="p-2 text-left">Description</th><th class="p-2 text-left">HSN/SAC</th><th class="p-2 text-left">Required Workers / Qty</th><th class="p-2 text-left">Unit</th><th class="p-2 text-left">Rate</th><th class="p-2 text-left">Amount</th><th></th></tr></thead><tbody id="itemRows">@foreach(old('items',$invoice->items->toArray()) as $i=>$item)<tr class="item-row"><td class="p-1"><input required name="items[{{ $i }}][description]" value="{{ data_get($item,'description') }}"></td><td class="p-1"><input name="items[{{ $i }}][hsn_sac_code]" value="{{ data_get($item,'hsn_sac_code') }}"></td><td class="p-1"><input class="qty" required min="0.01" step="0.01" type="number" name="items[{{ $i }}][quantity]" value="{{ data_get($item,'quantity',1) }}"></td><td class="p-1"><input name="items[{{ $i }}][unit]" value="{{ data_get($item,'unit') }}"></td><td class="p-1"><input class="rate" required min="0" step="0.01" type="number" name="items[{{ $i }}][rate]" value="{{ data_get($item,'rate',0) }}"></td><td class="p-1 font-bold amount">0.00</td><td class="p-1"><button type="button" class="remove-row text-red-600">Remove</button><input type="hidden" name="items[{{ $i }}][service_id]" value="{{ data_get($item,'service_id') }}"></td></tr>@endforeach</tbody></table></div><button type="button" id="addItem" class="btn-secondary mt-4">+ Add Item</button></section>
    <section class="card p-6"><h2 class="mb-4 text-lg font-black">4. Tax / GST</h2><div class="grid gap-4 md:grid-cols-3"><div><label>Discount Type</label><select name="discount_type"><option value="">No discount</option><option value="fixed" @selected(old('discount_type',$invoice->discount_type)=='fixed')>Fixed</option><option value="percentage" @selected(old('discount_type',$invoice->discount_type)=='percentage')>Percentage</option></select></div><div><label>Discount Value</label><input type="number" step="0.01" min="0" name="discount_value" value="{{ old('discount_value',$invoice->discount_value ?? 0) }}"></div><div><label>Tax Type *</label><select name="tax_type"><option value="none" @selected(old('tax_type',$invoice->tax_type)=='none')>No GST</option><option value="intra_state" @selected(old('tax_type',$invoice->tax_type)=='intra_state')>CGST + SGST</option><option value="inter_state" @selected(old('tax_type',$invoice->tax_type)=='inter_state')>IGST</option></select></div><div><label>Overall GST Rate %</label><input required type="number" min="0" max="100" step="0.01" name="tax_rate" value="{{ old('tax_rate',$invoice->tax_rate ?? 0) }}"></div><div><label>CGST Rate %</label><input type="number" min="0" max="100" step="0.01" name="cgst_rate" value="{{ old('cgst_rate',$invoice->cgst_rate ?? 0) }}"></div><div><label>SGST Rate %</label><input type="number" min="0" max="100" step="0.01" name="sgst_rate" value="{{ old('sgst_rate',$invoice->sgst_rate ?? 0) }}"></div><div><label>IGST Rate %</label><input type="number" min="0" max="100" step="0.01" name="igst_rate" value="{{ old('igst_rate',$invoice->igst_rate ?? 0) }}"></div><div><label>Round Off (+/-)</label><input type="number" step="0.01" name="round_off" value="{{ old('round_off',$invoice->round_off ?? 0) }}"></div></div><p class="mt-4 text-sm text-neutral-500">Totals shown while editing are estimates. The server recalculates every amount before saving.</p><p class="mt-2 text-xl font-black">Estimated total: ₹<span id="estimate">0.00</span></p></section>
    <section class="card p-6"><h2 class="mb-4 text-lg font-black">5. Bank / Payment Details</h2><div class="grid gap-4 md:grid-cols-2 xl:grid-cols-3">@foreach(['bank_holder_snapshot'=>'Account Holder','bank_name_snapshot'=>'Bank Name','bank_account_snapshot'=>'Account Number','bank_ifsc_snapshot'=>'IFSC','bank_branch_snapshot'=>'Branch','upi_id_snapshot'=>'UPI ID'] as $field=>$label)<div><label>{{ $label }}</label><input name="{{ $field }}" value="{{ old($field,$invoice->$field ?? match($field){'bank_holder_snapshot'=>$agency->bank_account_holder_name,'bank_name_snapshot'=>$agency->bank_name,'bank_account_snapshot'=>$agency->bank_account_number,'bank_ifsc_snapshot'=>$agency->bank_ifsc,'bank_branch_snapshot'=>$agency->bank_branch,'upi_id_snapshot'=>$agency->upi_id}) }}"></div>@endforeach</div><p class="mt-3 text-sm text-neutral-500">UPI QR, agency logo, signature and stamp are copied from Agency Settings when the invoice is created.</p></section>
    <section class="card p-6"><h2 class="mb-4 text-lg font-black">6. Notes / Terms</h2><div class="grid gap-4 md:grid-cols-2"><div><label>Invoice Notes</label><textarea name="notes">{{ old('notes',$invoice->notes) }}</textarea></div><div><label>Payment Terms</label><textarea name="terms">{{ old('terms',$invoice->terms) }}</textarea></div></div></section>
    <section class="card flex flex-wrap items-center justify-between gap-3 p-6"><div><h2 class="font-black">7. Review & Save</h2><p class="text-sm text-neutral-500">The saved draft can be previewed and generated as an A4 PDF.</p></div><button class="btn-primary">{{ $invoice->exists ? 'Save Invoice' : 'Create Draft Invoice' }}</button></section>
</form>
<script>
(() => {
 const rows=document.getElementById('itemRows');let next=Math.max(-1,...Array.from(rows.querySelectorAll('[name^="items["]')).map(x=>Number(x.name.match(/^items\[(\d+)\]/)?.[1]??-1)))+1;
 const recalc=()=>{let sum=0;rows.querySelectorAll('.item-row').forEach(r=>{let amount=(Number(r.querySelector('.qty').value)||0)*(Number(r.querySelector('.rate').value)||0);r.querySelector('.amount').textContent=amount.toFixed(2);sum+=amount});let form=rows.closest('form'),val=n=>Number(form.elements[n]?.value)||0,type=form.elements.discount_type.value,discount=type==='percentage'?sum*val('discount_value')/100:type==='fixed'?val('discount_value'):0,taxable=Math.max(0,sum-discount),tax=form.elements.tax_type.value;document.getElementById('estimate').textContent=(taxable+taxable*(tax==='intra_state'?(val('cgst_rate')+val('sgst_rate')):tax==='inter_state'?val('igst_rate'):0)/100+val('round_off')).toFixed(2)};
 rows.addEventListener('input',recalc);rows.addEventListener('click',e=>{if(e.target.classList.contains('remove-row')&&rows.children.length>1){e.target.closest('tr').remove();recalc()}});
 document.getElementById('addItem').onclick=()=>{let tr=document.createElement('tr');tr.className='item-row';tr.innerHTML=`<td class="p-1"><input required name="items[${next}][description]"></td><td class="p-1"><input name="items[${next}][hsn_sac_code]"></td><td class="p-1"><input class="qty" required min="0.01" step="0.01" type="number" name="items[${next}][quantity]" value="1"></td><td class="p-1"><input name="items[${next}][unit]"></td><td class="p-1"><input class="rate" required min="0" step="0.01" type="number" name="items[${next}][rate]" value="0"></td><td class="p-1 font-bold amount">0.00</td><td class="p-1"><button type="button" class="remove-row text-red-600">Remove</button><input type="hidden" name="items[${next}][service_id]"></td>`;rows.append(tr);next++};
 rows.closest('form').addEventListener('input',recalc);recalc();
 const customer=document.getElementById('customer'),assignment=document.getElementById('assignment'),agreement=document.getElementById('agreement'),requirement=document.getElementById('requirement');
 const setCustomer=()=>{let o=customer.selectedOptions[0];if(!o?.value)return;document.getElementById('customerName').value=o.dataset.name||'';document.getElementById('customerAddress').value=o.dataset.address||'';document.getElementById('customerMobile').value=o.dataset.mobile||'';document.getElementById('customerEmail').value=o.dataset.email||''};
 customer.addEventListener('change',setCustomer);
 const setCharge=o=>{if({{ $invoice->exists ? 'true' : 'false' }} || !o?.value)return;let r=rows.querySelector('.item-row'),d=r?.querySelector('[name$="[description]"]'),rate=r?.querySelector('.rate');if(!r||!d||!rate||d.value.trim())return;let salary=Number(o.dataset.salary)||0,charge=Number(o.dataset.charge)||0;if(salary>0){d.value='Monthly Worker Salary';rate.value=o.dataset.salary;let service=r.querySelector('[name$="[service_id]"]');if(service)service.value=o.dataset.service||'';if(charge>0){document.getElementById('addItem').click();r=rows.lastElementChild;d=r.querySelector('[name$="[description]"]');rate=r.querySelector('.rate')}}if(charge>0){d.value='Monthly Agency Service Charge';rate.value=o.dataset.charge;let service=r.querySelector('[name$="[service_id]"]');if(service)service.value=o.dataset.service||''}recalc()};
 assignment.addEventListener('change',()=>{let o=assignment.selectedOptions[0];if(o?.value){customer.value=o.dataset.customer;requirement.value=o.dataset.requirement||'';setCustomer();setCharge(o)}});
 agreement.addEventListener('change',()=>{let o=agreement.selectedOptions[0];if(o?.value){customer.value=o.dataset.customer;assignment.value=o.dataset.assignment||'';requirement.value=o.dataset.requirement||assignment.selectedOptions[0]?.dataset.requirement||'';setCustomer();setCharge(o)}});
})();
</script>
@endsection
