<?php
namespace App\Services;
use App\Enums\AssignmentStatus;use App\Enums\AvailabilityStatus;use App\Enums\ReplacementStatus;use App\Models\Assignment;use App\Models\ReplacementRequest;use App\Models\Worker;use Illuminate\Support\Facades\DB;use Illuminate\Support\Str;use Illuminate\Validation\ValidationException;
class ReplacementService
{
    public function __construct(private AssignmentService $assignments){}
    public function create(Assignment $assignment,array $data,int $actorId):ReplacementRequest{return DB::transaction(function()use($assignment,$data,$actorId){$assignment=Assignment::lockForUpdate()->findOrFail($assignment->id);if(!in_array($assignment->status,[AssignmentStatus::Active,AssignmentStatus::Confirmed]))throw ValidationException::withMessages(['assignment'=>'Only confirmed or active assignments can be replaced.']);$r=ReplacementRequest::create(['replacement_code'=>'PENDING-'.Str::uuid(),'assignment_id'=>$assignment->id,'customer_id'=>$assignment->customer_id,'customer_requirement_id'=>$assignment->customer_requirement_id,'old_worker_id'=>$assignment->worker_id,'reason'=>$data['reason'],'reason_details'=>$data['reason_details']??null,'requested_date'=>$data['requested_date'],'replacement_required_date'=>$data['replacement_required_date']??null,'status'=>ReplacementStatus::Requested,'requested_by'=>$actorId,'remarks'=>$data['remarks']??null]);$r->forceFill(['replacement_code'=>sprintf('HH-REP-%06d',$r->id)])->saveQuietly();$r->statusHistory()->create(['old_status'=>null,'new_status'=>ReplacementStatus::Requested->value,'changed_by'=>$actorId,'reason'=>'Replacement requested']);return $r->fresh();});}
    public function updateStatus(ReplacementRequest $replacement,ReplacementStatus $to,?string $reason,int $actorId):ReplacementRequest{return DB::transaction(function()use($replacement,$to,$reason,$actorId){$replacement=ReplacementRequest::lockForUpdate()->findOrFail($replacement->id);$allowed=['requested'=>['under_review','cancelled'],'under_review'=>['approved','rejected','cancelled'],'approved'=>['worker_search','shortlisted','cancelled'],'worker_search'=>['shortlisted','cancelled'],'shortlisted'=>['worker_search','cancelled'],'replacement_assigned'=>['completed'],'completed'=>[],'rejected'=>[],'cancelled'=>[]];if(!in_array($to->value,$allowed[$replacement->status->value],true))throw ValidationException::withMessages(['status'=>'Invalid replacement status transition.']);$old=$replacement->status->value;$extra=[];if($to===ReplacementStatus::Approved)$extra=['approved_by'=>$actorId,'approved_at'=>now()];if($to===ReplacementStatus::Completed)$extra=['completed_at'=>now()];$replacement->update(array_merge(['status'=>$to],$extra));$replacement->statusHistory()->create(['old_status'=>$old,'new_status'=>$to->value,'changed_by'=>$actorId,'reason'=>$reason]);return $replacement->fresh();});}
    public function assign(ReplacementRequest $replacement,Worker $worker,array $data,int $actorId):Assignment{return DB::transaction(function()use($replacement,$worker,$data,$actorId){$replacement=ReplacementRequest::lockForUpdate()->findOrFail($replacement->id);if(!in_array($replacement->status,[ReplacementStatus::Approved,ReplacementStatus::WorkerSearch,ReplacementStatus::Shortlisted]))throw ValidationException::withMessages(['status'=>'Replacement is not ready for worker assignment.']);if($worker->id===$replacement->old_worker_id)throw ValidationException::withMessages(['worker'=>'The current worker cannot be selected as their own replacement.']);$old=Assignment::lockForUpdate()->findOrFail($replacement->assignment_id);$new=$this->assignments->create($replacement->requirement,$worker,$data,$actorId);$this->assignments->markReplaced($old,$actorId,'Replacement worker assigned');Worker::lockForUpdate()->findOrFail($old->worker_id)->update(['availability_status'=>AvailabilityStatus::Available,'updated_by'=>$actorId]);$from=$replacement->status->value;$replacement->update(['status'=>ReplacementStatus::ReplacementAssigned,'new_worker_id'=>$worker->id,'replacement_assignment_id'=>$new->id]);$replacement->statusHistory()->create(['old_status'=>$from,'new_status'=>ReplacementStatus::ReplacementAssigned->value,'changed_by'=>$actorId,'reason'=>'Replacement worker selected']);return $new;});}
}
