@extends('layouts.admin')
@section('title',$agreement->exists?'Edit Agreement':'Create Agreement') @section('heading',$agreement->exists?'Edit Agreement':'Create Agreement') @section('subheading','Review auto-loaded records and capture a legal snapshot.')
@section('content')
@php($a=$selectedAssignment)
@if($agreement->exists&&$agreement->pdf_version)<div class="mb-5 rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm">This agreement already has PDF version {{ $agreement->pdf_version }}. Saving changes will not overwrite it; explicitly generate a new version afterward.</div>@endif
<form id="agreementForm" method="POST" action="{{ $agreement->exists?route('admin.agreements.update',$agreement):route('admin.agreements.store') }}">@csrf @if($agreement->exists)@method('PUT')@endif
<div class="card mb-6 overflow-x-auto p-2"><div class="flex min-w-max gap-1">@foreach(['source'=>'1. Source','agency'=>'2. Agency','customer'=>'3. Customer','service'=>'4. Worker & Service','financial'=>'5. Service Terms','terms'=>'6. Terms','signatures'=>'7. Signatures','review'=>'8. Review'] as $step=>$label)<button type="button" data-step="{{ $step }}" class="rounded-xl px-3 py-2 text-sm font-bold text-neutral-500 first:bg-charcoal-900 first:text-white">{{ $label }}</button>@endforeach</div></div>
<section data-panel="source" class="card p-6"><h2 class="mb-4 font-black">Agreement Source</h2><div class="grid gap-5 md:grid-cols-3"><div><label>Assignment (preferred)</label><select id="assignmentSelect" name="assignment_id"><option value="">Manual agreement</option>@foreach($assignments as $item)<option value="{{ $item->id }}" @selected(old('assignment_id',$agreement->assignment_id??$a?->id)==$item->id)>{{ $item->assignment_code }} · {{ $item->customer->name }} · {{ $item->worker->name }}</option>@endforeach</select><p class="mt-1 text-xs text-neutral-500">Changing this reloads trusted assignment data.</p></div>@if($a)<div><label>Customer</label><input readonly value="{{ $a->customer->name }}"><input type="hidden" name="customer_id" value="{{ $a->customer_id }}"></div><div><label>Requirement</label><input readonly value="{{ $a->requirement->requirement_code }}"><input type="hidden" name="customer_requirement_id" value="{{ $a->customer_requirement_id }}"><input type="hidden" name="worker_id" value="{{ $a->worker_id }}"></div>@else<div><label>Customer</label><select name="customer_id"><option value="">Select</option>@foreach($customers as $c)<option value="{{ $c->id }}" @selected(old('customer_id',$agreement->customer_id)==$c->id)>{{ $c->customer_code }} · {{ $c->name }}</option>@endforeach</select></div><div><label>Requirement</label><select name="customer_requirement_id"><option value="">Optional</option>@foreach($requirements as $r)<option value="{{ $r->id }}" @selected(old('customer_requirement_id',$agreement->customer_requirement_id)==$r->id)>{{ $r->requirement_code }} · {{ $r->service->name }}</option>@endforeach</select></div>@endif<div><label>Agreement Date</label><input required type="date" name="agreement_date" value="{{ old('agreement_date',$agreement->agreement_date?->format('Y-m-d')??today()->format('Y-m-d')) }}"></div></div></section>
<section data-panel="agency" class="card hidden p-6"><h2 class="mb-4 font-black">Agency Details</h2><p class="text-sm text-neutral-500">Business name, address, phone, email, GST, logo, signature, and stamp are snapshotted from Agency Settings when saved.</p><div class="mt-5"><label>Authorized Person</label><input name="authorized_person_name" value="{{ old('authorized_person_name',$agreement->authorized_person_name??$a?->assignedBy?->name) }}"></div></section>
<section data-panel="customer" class="card hidden p-6"><h2 class="mb-4 font-black">Customer Snapshot</h2><div class="grid gap-5 md:grid-cols-2"><div><label>Customer Name</label><input name="customer_name_snapshot" value="{{ old('customer_name_snapshot',$agreement->customer_name_snapshot??$a?->customer->name) }}"></div><div><label>Mobile</label><input name="customer_mobile_snapshot" value="{{ old('customer_mobile_snapshot',$agreement->customer_mobile_snapshot??$a?->customer->mobile_number) }}"></div><div><label>Email</label><input type="email" name="customer_email_snapshot" value="{{ old('customer_email_snapshot',$agreement->customer_email_snapshot??$a?->customer->email) }}"></div><div><label>Agreement-specific Address</label><textarea name="customer_address_snapshot">{{ old('customer_address_snapshot',$agreement->customer_address_snapshot??($a ? collect([$a->customer->address_line_1,$a->customer->address_line_2,$a->customer->location,$a->customer->city,$a->customer->state,$a->customer->pincode,$a->customer->country])->filter()->join(', ') : '')) }}</textarea></div></div></section>
<section data-panel="service" class="card hidden p-6"><h2 class="mb-4 font-black">Worker & Service Details</h2><div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">@foreach([['Worker',$agreement->worker_name_snapshot??$a?->worker->name],['Worker Code',$agreement->worker_code_snapshot??$a?->worker->worker_code],['Service',$agreement->service?->name??$a?->service->name],['Duty Type',$agreement->dutyType?->name??$a?->dutyType?->name],['Gender Preference',$agreement->gender_preference??$a?->requirement->required_gender],['House Type',$agreement->house_type??$a?->requirement->householdDetail?->house_type]] as [$label,$value])<div><p class="text-xs font-bold uppercase text-neutral-400">{{ $label }}</p><p class="mt-1 font-semibold">{{ str($value)->replace('_',' ')->headline()?:'—' }}</p></div>@endforeach</div></section>
<section data-panel="financial" class="card hidden p-6"><h2 class="mb-4 font-black">Financial & Service Terms</h2><div class="grid gap-5 md:grid-cols-2 lg:grid-cols-3"><div><label>Monthly Salary</label><input type="number" min="0" step=".01" name="monthly_salary" value="{{ old('monthly_salary',$agreement->monthly_salary??$a?->monthly_salary) }}"></div><div><label>Monthly Agency Service Charge</label><input type="number" min="0" step=".01" name="monthly_agency_service_charge" value="{{ old('monthly_agency_service_charge',$agreement->monthly_agency_service_charge??$a?->agency_service_charge) }}"></div><div><label>Monthly Leave / Off</label><input name="monthly_leave_text" value="{{ old('monthly_leave_text',$agreement->monthly_leave_text??$a?->requirement->workingCondition?->leave_details) }}" placeholder="e.g. 2 Days"></div><div><label>Start Date</label><input type="date" name="start_date" value="{{ old('start_date',$agreement->start_date?->format('Y-m-d')??$a?->assignment_start_date?->format('Y-m-d')) }}"></div><div><label>End Date</label><input type="date" name="end_date" value="{{ old('end_date',$agreement->end_date?->format('Y-m-d')??$a?->assignment_end_date?->format('Y-m-d')) }}"></div><div><label>Tenure</label><input name="tenure_text" value="{{ old('tenure_text',$agreement->tenure_text) }}" placeholder="Calculated if blank"></div><div><label>Working Hours</label><input name="working_hours_text" value="{{ old('working_hours_text',$agreement->working_hours_text??$a?->working_hours_text) }}"></div><div class="md:col-span-2"><label>Work Location</label><input name="work_location" value="{{ old('work_location',$agreement->work_location??$a?->work_location) }}"></div></div></section>
<section data-panel="terms" class="card hidden p-6"><h2 class="mb-2 font-black">Terms & Conditions</h2><p class="mb-4 text-sm text-neutral-500">Loaded from the default template and stored as an independent snapshot.</p><textarea required name="terms_snapshot" rows="24">{{ old('terms_snapshot',$agreement->terms_snapshot??$template?->terms_content) }}</textarea></section>
<section data-panel="signatures" class="card hidden p-6"><h2 class="font-black">Digital Signature Capture</h2><p class="mt-2 text-sm text-neutral-500">Save the draft first, then upload or draw signatures from the agreement detail page. This is not described as a government-certified eSign.</p></section>
<section data-panel="review" class="card hidden p-6"><h2 class="font-black">Review & Save</h2><p class="mt-2 text-sm">Saving creates immutable customer, worker, agency, service, and terms snapshots. PDF generation is a separate explicit action.</p><button class="btn-primary mt-5">{{ $agreement->exists?'Update Agreement':'Create Agreement Draft' }}</button></section></form>
<script>(()=>{const bs=[...document.querySelectorAll('[data-step]')],ps=[...document.querySelectorAll('[data-panel]')];const show=i=>{bs.forEach((b,n)=>b.className='rounded-xl px-3 py-2 text-sm font-bold '+(i===n?'bg-charcoal-900 text-white':'text-neutral-500'));ps.forEach(p=>p.classList.toggle('hidden',p.dataset.panel!==bs[i].dataset.step))};bs.forEach((b,i)=>b.onclick=()=>show(i));document.getElementById('assignmentSelect')?.addEventListener('change',e=>{if(e.target.value)location.href='{{ route('admin.agreements.create') }}?assignment='+e.target.value});show(0)})()</script>
@endsection
