<?php
namespace Tests\Feature;
use App\Enums\AgreementStatus;use App\Models\Agreement;use App\Models\AgreementTemplate;use App\Models\Assignment;use App\Models\CustomerRequirement;use App\Models\DocumentShareLink;use App\Models\DutyType;use App\Models\Role;use App\Models\Service;use App\Models\User;use App\Models\Worker;use App\Services\AgreementPdfService;use App\Services\AgreementService;use App\Services\AssignmentService;use App\Services\CustomerManager;use Database\Seeders\DatabaseSeeder;use Illuminate\Foundation\Testing\RefreshDatabase;use Illuminate\Http\UploadedFile;use Illuminate\Support\Facades\Storage;use Illuminate\Validation\ValidationException;use Tests\TestCase;
class StageFiveTest extends TestCase
{
 use RefreshDatabase;private int $seq=0;protected function setUp():void{parent::setUp();$this->seed(DatabaseSeeder::class);Storage::fake('local');}
 public function test_super_admin_can_create_agreement_from_assignment_with_snapshots_and_prefilled_financials():void{$a=$this->assignment();$response=$this->actingAs($this->admin())->post(route('admin.agreements.store'),$this->agreementData($a));$response->assertSessionHasNoErrors()->assertRedirect();$g=Agreement::firstOrFail();$this->assertMatchesRegularExpression('/^HH-AGR-\d{6}$/',$g->agreement_code);$this->assertSame($a->customer_id,$g->customer_id);$this->assertSame($a->worker_id,$g->worker_id);$this->assertSame($a->monthly_salary,$g->monthly_salary);$this->assertNotNull($g->agency_name_snapshot);$this->assertSame($a->customer->name,$g->customer_name_snapshot);$this->assertSame('Original terms',$g->terms_snapshot);}
 public function test_staff_without_permission_cannot_create_agreement():void{$a=$this->assignment();$staff=User::factory()->create(['role_id'=>Role::where('slug','staff')->firstOrFail()->id,'is_active'=>true]);$this->actingAs($staff)->post(route('admin.agreements.store'),$this->agreementData($a))->assertForbidden();}
 public function test_assignment_customer_or_worker_mismatch_is_rejected():void{$a=$this->assignment();$other=$this->assignment();$data=array_merge($this->agreementData($a),['customer_id'=>$other->customer_id,'worker_id'=>$other->worker_id]);$this->expectException(ValidationException::class);app(AgreementService::class)->create($data,$this->admin()->id);}
 public function test_assignment_cannot_accidentally_receive_two_current_agreements():void{$a=$this->assignment();$service=app(AgreementService::class);$service->create($this->agreementData($a),$this->admin()->id);$this->expectException(ValidationException::class);$service->create($this->agreementData($a),$this->admin()->id);}
 public function test_template_change_does_not_change_terms_snapshot():void{$g=$this->agreement();$template=AgreementTemplate::firstOrFail();$template->update(['terms_content'=>'Changed later']);$this->assertSame('Original terms',$g->fresh()->terms_snapshot);}
 public function test_pdf_generation_download_and_version_safety():void{$g=$this->agreement();$pdf=app(AgreementPdfService::class);$pdf->generate($g,$this->admin()->id);$g=$g->fresh();$this->assertSame(AgreementStatus::Generated,$g->status);$this->assertSame(1,$g->pdf_version);Storage::disk('local')->assertExists($g->pdf_path);$this->actingAs($this->admin())->get(route('admin.agreements.download',$g))->assertOk()->assertHeader('content-type','application/pdf');$first=$g->pdf_path;$pdf->generate($g,$this->admin()->id);$g=$g->fresh();$this->assertSame(2,$g->pdf_version);$this->assertNotSame($first,$g->pdf_path);Storage::disk('local')->assertExists($first);$this->assertDatabaseCount('agreement_versions',2);}
 public function test_unauthorized_user_cannot_download_private_pdf():void{$g=$this->agreement();app(AgreementPdfService::class)->generate($g,$this->admin()->id);$staff=User::factory()->create(['role_id'=>Role::where('slug','staff')->firstOrFail()->id,'is_active'=>true]);$this->actingAs($staff)->get(route('admin.agreements.download',$g))->assertForbidden();}
 public function test_customer_and_agency_signature_uploads_work_and_status_history_is_created():void{$g=$this->agreement();app(AgreementPdfService::class)->generate($g,$this->admin()->id);$service=app(AgreementService::class);$service->transition($g->fresh(),AgreementStatus::Sent,$this->admin()->id,'Sent');$service->storeSignature($g->fresh(),'customer',['signature'=>UploadedFile::fake()->image('customer.png')],$this->admin()->id);$service->storeSignature($g->fresh(),'agency',['signature'=>UploadedFile::fake()->image('agency.png'),'stamp'=>UploadedFile::fake()->image('stamp.png')],$this->admin()->id);$g=$g->fresh();$this->assertNotNull($g->customer_signature_path);$this->assertNotNull($g->agency_signature_path);$this->assertNotNull($g->agency_stamp_path);$this->assertSame(AgreementStatus::Signed,$g->status);$this->assertDatabaseHas('agreement_status_history',['agreement_id'=>$g->id,'new_status'=>'signed']);}
 public function test_signed_agreement_restricts_critical_editing_and_pdf_overwrite():void{$g=$this->agreement();$g->update(['status'=>'signed']);$this->expectException(ValidationException::class);app(AgreementService::class)->update($g,$this->agreementData($g->assignment),$this->admin()->id);}
 public function test_share_token_uses_public_controller_without_exposing_private_path():void{$g=$this->agreement();app(AgreementPdfService::class)->generate($g,$this->admin()->id);$response=$this->actingAs($this->admin())->post(route('admin.agreements.share.whatsapp',$g));$response->assertRedirect();$link=DocumentShareLink::firstOrFail();$this->assertStringNotContainsString('storage/app/private',$response->headers->get('Location'));$this->get(route('shared.agreements.download',$link->token))->assertOk()->assertHeader('content-type','application/pdf');}
 public function test_expired_share_token_is_rejected():void{$g=$this->agreement();app(AgreementPdfService::class)->generate($g,$this->admin()->id);$link=DocumentShareLink::create(['token'=>str_repeat('a',64),'document_type'=>'agreement','document_id'=>$g->id,'expires_at'=>now()->subMinute(),'is_active'=>true]);$this->get(route('shared.agreements.download',$link->token))->assertGone();}
 public function test_assignment_customer_worker_and_dashboard_pages_show_agreement():void{$g=$this->agreement();$admin=$this->admin();$this->actingAs($admin)->get(route('admin.assignments.show',$g->assignment))->assertOk()->assertSee($g->agreement_code);$this->actingAs($admin)->get(route('admin.customers.show',$g->customer))->assertOk()->assertSee($g->agreement_code);$this->actingAs($admin)->get(route('admin.workers.show',$g->worker))->assertOk()->assertSee($g->agreement_code);$this->actingAs($admin)->get(route('admin.dashboard'))->assertOk()->assertSee('Total Agreements');}
 public function test_agreement_creation_and_document_pages_render():void{$a=$this->assignment();$g=app(AgreementService::class)->create($this->agreementData($a),$this->admin()->id);$admin=$this->admin();foreach([route('admin.agreements.index'),route('admin.agreements.create'),route('admin.assignments.agreement.create',$a),route('admin.agreements.show',$g),route('admin.agreements.edit',$g),route('admin.agreements.preview',$g),route('admin.agreements.print',$g),route('admin.agreement-templates.index'),route('admin.agreement-templates.edit',AgreementTemplate::first())] as $url){$level=ob_get_level();$this->actingAs($admin)->get($url)->assertOk();$this->assertSame($level,ob_get_level(),"Output buffer leaked while rendering {$url}");}}
 private function agreement():Agreement{$a=$this->assignment();return app(AgreementService::class)->create($this->agreementData($a),$this->admin()->id);}private function agreementData(Assignment $a):array{return ['assignment_id'=>$a->id,'customer_id'=>$a->customer_id,'customer_requirement_id'=>$a->customer_requirement_id,'worker_id'=>$a->worker_id,'agreement_date'=>today()->format('Y-m-d'),'start_date'=>$a->assignment_start_date->format('Y-m-d'),'end_date'=>$a->assignment_end_date?->format('Y-m-d'),'monthly_salary'=>$a->monthly_salary,'monthly_agency_service_charge'=>$a->agency_service_charge,'working_hours_text'=>$a->working_hours_text,'monthly_leave_text'=>'2 Days','work_location'=>$a->work_location,'terms_snapshot'=>'Original terms'];}
 private function assignment():Assignment{$r=$this->requirement();$w=$this->worker($this->service());return app(AssignmentService::class)->create($r,$w,['assignment_start_date'=>today()->format('Y-m-d'),'assignment_end_date'=>today()->addMonths(6)->format('Y-m-d'),'duty_type_id'=>$this->duty()->id,'working_hours_text'=>'9 AM - 6 PM','monthly_salary'=>18000,'agency_service_charge'=>2000,'work_location'=>'Mumbai'],$this->admin()->id);}private function requirement():CustomerRequirement{$data=['registration_date'=>today()->format('Y-m-d'),'name'=>'Agreement Customer '.uniqid(),'mobile_number'=>(string)random_int(7000000000,9999999999),'address_line_1'=>'Customer Address','city'=>'Mumbai','state'=>'Maharashtra','country'=>'India','status'=>'active','service_id'=>$this->service()->id,'duty_type_id'=>$this->duty()->id,'required_gender'=>'female','number_of_persons'=>1,'requirement_status'=>'open','monthly_salary_budget'=>18000,'monthly_agency_service_charge'=>2000,'preferred_start_date'=>today()->format('Y-m-d'),'working_hours_text'=>'9 AM - 6 PM','house_type'=>'2_bhk'];return app(CustomerManager::class)->register($data,$this->admin()->id)->requirements()->firstOrFail();}private function worker(Service $service):Worker{$this->seq++;$w=Worker::create(['worker_code'=>'HH-WRK-A'.sprintf('%05d',$this->seq),'registration_date'=>today(),'name'=>'Agreement Worker '.$this->seq,'mobile_number'=>'800000'.sprintf('%04d',$this->seq),'address_line_1'=>'Worker Address','city'=>'Mumbai','state'=>'Maharashtra','country'=>'India','age'=>30,'gender'=>'female','years_of_experience'=>3,'salary_expectation'=>15000,'preferred_duty_type_id'=>$this->duty()->id,'availability_status'=>'available','worker_status'=>'active']);$w->services()->attach($service);return $w;}private function service():Service{return Service::firstOrFail();}private function duty():DutyType{return DutyType::firstOrFail();}private function admin():User{return User::whereHas('role',fn($q)=>$q->where('slug','super-admin'))->firstOrFail();}
}
