@extends('layouts.admin')
@section('title',$interview->exists ? 'Edit Interview' : 'Add Interview')
@section('heading',$interview->exists ? 'Edit Interview' : 'Add Interview')
@section('subheading','Capture the worker assessment and outcome.')
@section('content')
<form class="card grid gap-4 p-6 md:grid-cols-2" method="POST" action="{{ $interview->exists ? route('admin.worker-interviews.update',$interview) : route('admin.worker-interviews.store') }}">@csrf @if($interview->exists) @method('PUT') @endif
<div><label>Worker</label><select name="worker_id" required>@foreach($workers as $worker)<option value="{{ $worker->id }}" @selected(old('worker_id',$interview->worker_id)==$worker->id)>{{ $worker->name }} ({{ $worker->worker_code }})</option>@endforeach</select></div><div><label>Interview date</label><input type="datetime-local" name="interview_date" value="{{ old('interview_date',$interview->interview_date?->format('Y-m-d\TH:i')) }}"></div>
<div><label>Interviewer</label><select name="interviewer_user_id"><option value="">Select</option>@foreach($interviewers as $user)<option value="{{ $user->id }}" @selected(old('interviewer_user_id',$interview->interviewer_user_id)==$user->id)>{{ $user->name }}</option>@endforeach</select></div><div><label>Result</label><select name="result" required>@foreach($results as $result)<option value="{{ $result->value }}" @selected(old('result',$interview->result?->value)===$result->value)>{{ $result->label() }}</option>@endforeach</select></div>
<div><label>Service</label><select name="service_id"><option value="">Select</option>@foreach($services as $service)<option value="{{ $service->id }}" @selected(old('service_id',$interview->service_id)==$service->id)>{{ $service->name }}</option>@endforeach</select></div><div><label>Preferred duty</label><select name="preferred_duty_type_id"><option value="">Select</option>@foreach($dutyTypes as $type)<option value="{{ $type->id }}" @selected(old('preferred_duty_type_id',$interview->preferred_duty_type_id)==$type->id)>{{ $type->name }}</option>@endforeach</select></div>
<div><label>Expected salary</label><input type="number" step="0.01" min="0" name="expected_salary" value="{{ old('expected_salary',$interview->expected_salary) }}"></div><div><label>Preferred location</label><input name="preferred_location" value="{{ old('preferred_location',$interview->preferred_location) }}"></div>
<textarea class="md:col-span-2" name="experience_assessment" rows="3" placeholder="Experience assessment">{{ old('experience_assessment',$interview->experience_assessment) }}</textarea><textarea class="md:col-span-2" name="skills_assessment" rows="3" placeholder="Skills assessment">{{ old('skills_assessment',$interview->skills_assessment) }}</textarea><textarea class="md:col-span-2" name="communication_assessment" rows="3" placeholder="Communication assessment">{{ old('communication_assessment',$interview->communication_assessment) }}</textarea><textarea class="md:col-span-2" name="interview_notes" rows="3" placeholder="Interview notes">{{ old('interview_notes',$interview->interview_notes) }}</textarea><button class="btn-primary md:col-span-2">Save Interview</button>
</form>
@endsection
