@extends('layouts.admin')
@section('title','Worker Interviews')
@section('heading','Worker Interviews')
@section('subheading','Record and review worker interview assessments.')
@section('actions')@if(auth()->user()->hasPermission('worker-interviews.create'))<a class="btn-primary" href="{{ route('admin.worker-interviews.create') }}">Add Interview</a>@endif@endsection
@section('content')
<form class="card mb-5 flex flex-wrap gap-3 p-4" method="GET"><select name="result"><option value="">All results</option>@foreach($results as $result)<option value="{{ $result->value }}" @selected(request('result') === $result->value)>{{ str($result->value)->headline() }}</option>@endforeach</select><select name="service"><option value="">All services</option>@foreach($services as $service)<option value="{{ $service->id }}" @selected(request('service') == $service->id)>{{ $service->name }}</option>@endforeach</select><select name="interviewer"><option value="">All interviewers</option>@foreach($interviewers as $interviewer)<option value="{{ $interviewer->id }}" @selected(request('interviewer') == $interviewer->id)>{{ $interviewer->name }}</option>@endforeach</select><input type="date" name="date" value="{{ request('date') }}"><button class="btn-primary">Filter</button></form>
<div class="card overflow-x-auto"><table class="w-full min-w-[900px] text-left text-sm"><thead><tr><th class="p-3">Worker</th><th>Date</th><th>Service</th><th>Interviewer</th><th>Result</th><th>Actions</th></tr></thead><tbody class="divide-y">@forelse($interviews as $interview)<tr><td class="p-3">{{ $interview->worker?->name }}<div class="text-xs text-neutral-500">{{ $interview->worker?->worker_code }}</div></td><td>{{ $interview->interview_date?->format('d M Y') ?: '—' }}</td><td>{{ $interview->service?->name ?: '—' }}</td><td>{{ $interview->interviewer?->name ?: '—' }}</td><td>{{ str($interview->result->value)->headline() }}</td><td>@if(auth()->user()->hasPermission('worker-interviews.edit'))<a class="font-bold text-gold-600" href="{{ route('admin.worker-interviews.edit',$interview) }}">Edit</a>@endif</td></tr>@empty<tr><td colspan="6" class="p-8 text-center text-neutral-500">No interviews found.</td></tr>@endforelse</tbody></table></div><div class="mt-4">{{ $interviews->links() }}</div>
@endsection
