<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration { public function up():void{
Schema::create('agreement_templates',function(Blueprint $t){$t->id();$t->string('name');$t->string('slug')->unique();$t->string('title');$t->text('intro_text')->nullable();$t->longText('terms_content');$t->boolean('is_default')->default(false)->index();$t->boolean('is_active')->default(true)->index();$t->timestamps();});
Schema::create('agreements',function(Blueprint $t){$t->id();$t->string('agreement_code')->unique();$t->foreignId('customer_id')->constrained('customers')->restrictOnDelete();$t->foreignId('customer_requirement_id')->nullable()->constrained('customer_requirements')->nullOnDelete();$t->foreignId('assignment_id')->nullable()->constrained('assignments')->nullOnDelete();$t->foreignId('worker_id')->nullable()->constrained('workers')->nullOnDelete();$t->foreignId('service_id')->nullable()->constrained('services')->nullOnDelete();$t->foreignId('duty_type_id')->nullable()->constrained('duty_types')->nullOnDelete();$t->date('agreement_date')->index();$t->date('start_date')->nullable();$t->date('end_date')->nullable();$t->string('tenure_text')->nullable();$t->decimal('monthly_salary',12,2)->nullable();$t->decimal('monthly_agency_service_charge',12,2)->nullable();$t->string('working_hours_text')->nullable();$t->string('monthly_leave_text')->nullable();$t->string('work_location')->nullable();$t->string('gender_preference')->nullable();$t->string('house_type')->nullable();$t->string('status')->default('draft')->index();$t->longText('terms_snapshot')->nullable();$t->string('customer_name_snapshot')->nullable();$t->text('customer_address_snapshot')->nullable();$t->string('customer_mobile_snapshot',30)->nullable();$t->string('customer_email_snapshot')->nullable();$t->string('worker_name_snapshot')->nullable();$t->string('worker_code_snapshot')->nullable();$t->string('agency_name_snapshot')->nullable();$t->text('agency_address_snapshot')->nullable();$t->string('agency_phone_snapshot',30)->nullable();$t->string('agency_email_snapshot')->nullable();$t->string('agency_gst_snapshot',30)->nullable();$t->string('agency_logo_path')->nullable();$t->string('customer_signature_path')->nullable();$t->timestamp('customer_signed_at')->nullable();$t->string('authorized_person_name')->nullable();$t->string('agency_signature_path')->nullable();$t->string('agency_stamp_path')->nullable();$t->timestamp('agency_signed_at')->nullable();$t->string('pdf_path')->nullable();$t->unsignedInteger('pdf_version')->default(0);$t->timestamp('pdf_generated_at')->nullable();$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->foreignId('updated_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();$t->index(['assignment_id','status']);});
Schema::create('agreement_status_history',function(Blueprint $t){$t->id();$t->foreignId('agreement_id')->constrained('agreements')->cascadeOnDelete();$t->string('old_status')->nullable();$t->string('new_status');$t->foreignId('changed_by')->nullable()->constrained('users')->nullOnDelete();$t->text('reason')->nullable();$t->timestamp('created_at')->useCurrent();});
Schema::create('agreement_versions',function(Blueprint $t){$t->id();$t->foreignId('agreement_id')->constrained('agreements')->cascadeOnDelete();$t->unsignedInteger('version_number');$t->json('snapshot_json');$t->string('pdf_path');$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('created_at')->useCurrent();$t->unique(['agreement_id','version_number']);});
Schema::create('document_share_links',function(Blueprint $t){$t->id();$t->string('token',64)->unique();$t->string('document_type')->index();$t->unsignedBigInteger('document_id')->index();$t->timestamp('expires_at')->nullable()->index();$t->boolean('is_active')->default(true);$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('created_at')->useCurrent();});
}public function down():void{Schema::dropIfExists('document_share_links');Schema::dropIfExists('agreement_versions');Schema::dropIfExists('agreement_status_history');Schema::dropIfExists('agreements');Schema::dropIfExists('agreement_templates');}};
