@extends('layouts.admin')
@section('title',$requirement->requirement_code) @section('heading','Service Requirement') @section('subheading',$requirement->requirement_code.' · '.$requirement->customer->name)
@section('actions')<div class="flex gap-2">@if(auth()->user()->hasPermission('worker-matching.view'))<a class="btn-primary" href="{{ route('admin.customer-requirements.matching',$requirement) }}">Find Worker</a>@endif @if(auth()->user()->hasPermission('customer-requirements.edit'))<a class="btn-secondary" href="{{ route('admin.customer-requirements.edit',$requirement) }}">Edit</a>@endif<a class="btn-secondary" href="{{ route('admin.customers.show',$requirement->customer) }}">Customer</a></div>@endsection
@section('content')
@php
$h=$requirement->householdDetail;$a=$requirement->accommodationDetail;$w=$requirement->workingCondition;$p=$requirement->workerPreference;
$yn=fn($v)=>is_null($v)?'Not specified':($v?'Yes':'No');
@endphp
<div class="grid gap-6 xl:grid-cols-2"><section class="card p-6"><h2 class="mb-5 font-black">Requirement</h2><div class="grid gap-4 sm:grid-cols-2">@foreach([['Customer',$requirement->customer->name.' ('.$requirement->customer->customer_code.')'],['Requirement Code',$requirement->requirement_code],['Service',$requirement->service->name],['Duty Type',$requirement->dutyType?->name],['Required Gender',str($requirement->required_gender)->headline()],['Persons',$requirement->number_of_persons],['Salary Budget',$requirement->monthly_salary_budget?'₹'.number_format((float)$requirement->monthly_salary_budget):null],['Agency Charge',$requirement->monthly_agency_service_charge?'₹'.number_format((float)$requirement->monthly_agency_service_charge):null],['Preferred Start',$requirement->preferred_start_date?->format('d M Y')],['Status',$requirement->requirement_status->label()]] as [$label,$value])<div><p class="text-xs font-bold uppercase text-neutral-400">{{ $label }}</p><p class="mt-1 font-semibold">{{ $value ?: '—' }}</p></div>@endforeach</div><div class="mt-5"><p class="text-xs font-bold uppercase text-neutral-400">Work Description</p><p class="mt-1 whitespace-pre-line">{{ $requirement->detailed_work_description ?: '—' }}</p></div><div class="mt-5"><p class="text-xs font-bold uppercase text-neutral-400">Special Instructions</p><p class="mt-1 whitespace-pre-line">{{ $requirement->special_instructions ?: '—' }}</p></div></section>
<section class="card p-6"><h2 class="mb-5 font-black">Household Details</h2><div class="grid gap-4 sm:grid-cols-2">@foreach([['House Type',str($h?->house_type)->replace('_',' ')->upper()],['Custom House Type',$h?->custom_house_type],['Family Members',$h?->total_family_members],['Adults',$h?->adults_count],['Children',$h?->children_count],['Elderly',$h?->elderly_count],['Patients',$h?->patients_count],['Food Preference',str($h?->food_preference)->headline()],['Pets at Home',$yn($h?->pets_at_home)],['Lift Available',$yn($h?->lift_available)],['Outside Travel Required',$yn($h?->outside_travel_required)]] as [$label,$value])<div><p class="text-xs font-bold uppercase text-neutral-400">{{ $label }}</p><p class="mt-1">{{ $value ?: '—' }}</p></div>@endforeach</div></section>
<section class="card p-6"><h2 class="mb-5 font-black">Accommodation & Food</h2><div class="grid gap-4 sm:grid-cols-2">@foreach([['Accommodation',str($a?->accommodation_provided)->headline()],['Room',str($a?->room_type)->headline()],['Bathroom',str($a?->bathroom_type)->headline()],['Food',str($a?->food_provided)->headline()],['Breakfast',$yn($a?->breakfast_provided)],['Lunch',$yn($a?->lunch_provided)],['Dinner',$yn($a?->dinner_provided)],['Tea / Snacks',$yn($a?->tea_snacks_provided)],['Other Food Details',$a?->other_food_details],['Notes',$a?->accommodation_notes]] as [$label,$value])<div><p class="text-xs font-bold uppercase text-neutral-400">{{ $label }}</p><p class="mt-1">{{ $value ?: '—' }}</p></div>@endforeach</div></section>
<section class="card p-6"><h2 class="mb-5 font-black">Working Conditions</h2><div class="grid gap-4 sm:grid-cols-2">@foreach([['Working Hours',$w?->working_hours_text],['Start Time',$w?->work_start_time],['End Time',$w?->work_end_time],['Wake-Up Time',$w?->expected_wakeup_time],['Sleep Time',$w?->expected_sleep_time],['Afternoon Rest',$yn($w?->afternoon_rest)],['Rest Duration',$w?->rest_duration_hours],['Monthly Leave Days',$w?->monthly_leave_days],['Leave Details',$w?->leave_details],['Night Duty',$yn($w?->night_duty_required)],['Early Morning Work',$yn($w?->early_morning_work_required)],['Early Morning Details',$w?->early_morning_work_details]] as [$label,$value])<div><p class="text-xs font-bold uppercase text-neutral-400">{{ $label }}</p><p class="mt-1">{{ $value === null || $value === '' ? '—' : $value }}</p></div>@endforeach</div></section>
<section class="card p-6"><h2 class="mb-5 font-black">Worker Preferences</h2><div class="grid gap-4 sm:grid-cols-2">@foreach([['Age Range',($p?->preferred_age_min||$p?->preferred_age_max)?(($p?->preferred_age_min?:'Any').' – '.($p?->preferred_age_max?:'Any')):null],['Experience',$p?->experience_requirement?->label()],['Language',$p?->language_preference],['Specific Skills',$p?->specific_skills],['Other Work',$p?->other_work_expected],['Notes',$p?->worker_preference_notes]] as [$label,$value])<div><p class="text-xs font-bold uppercase text-neutral-400">{{ $label }}</p><p class="mt-1 whitespace-pre-line">{{ $value ?: '—' }}</p></div>@endforeach</div></section>
<section class="card p-6"><h2 class="mb-5 font-black">Status History</h2><div class="space-y-4">@foreach($requirement->statusHistory->sortByDesc('created_at') as $history)<div class="border-l-2 border-gold-500 pl-4"><strong>{{ str($history->new_status)->headline() }}</strong><p class="text-sm text-neutral-500">{{ $history->changedBy?->name ?: 'System' }} · {{ $history->created_at->format('d M Y, h:i A') }}</p>@if($history->reason)<p class="mt-1 text-sm">{{ $history->reason }}</p>@endif</div>@endforeach</div></section></div>
<div class="mt-6 grid gap-6 xl:grid-cols-2"><section class="card p-6"><h2 class="mb-4 font-black">Shortlisted Workers</h2>@forelse($requirement->workerShortlists as $s)<div class="mb-3 rounded-xl bg-neutral-50 p-3"><strong>{{ $s->worker->name }}</strong><p class="text-sm">{{ $s->worker->worker_code }} · {{ $s->status->label() }}</p><a class="text-sm font-bold text-gold-500" href="{{ route('admin.assignments.create',[$requirement,$s->worker]) }}">Assign Worker</a></div>@empty<p>No workers shortlisted.</p>@endforelse</section><section class="card p-6"><h2 class="mb-4 font-black">Assignments</h2>@forelse($requirement->assignments as $a)<a class="block py-2" href="{{ route('admin.assignments.show',$a) }}">{{ $a->assignment_code }} · {{ $a->worker->name }} · {{ $a->status->label() }}</a>@empty<p>No assignments.</p>@endforelse</section><section class="card p-6 xl:col-span-2"><h2 class="mb-4 font-black">Replacement History</h2>@forelse($requirement->replacementRequests as $r)<a class="block py-2" href="{{ route('admin.replacements.show',$r) }}">{{ $r->replacement_code }} · {{ $r->oldWorker->name }} → {{ $r->newWorker?->name?:'Pending' }}</a>@empty<p>No replacements.</p>@endforelse</section></div>
<section class="card mt-6 p-6"><div class="mb-4 flex flex-wrap items-center justify-between gap-2"><h2 class="font-black">Customer Registration Form</h2>@if(auth()->user()->hasPermission('customer-registration-documents.generate'))<a class="btn-primary" href="{{ route('admin.customer-requirements.registration-form.preview',$requirement) }}">Generate Registration Form</a>@endif</div><p class="text-sm text-neutral-500">Generate a versioned snapshot using this selected requirement.</p><div class="mt-4 divide-y">@forelse($requirement->generatedDocuments as $document)<div class="flex flex-wrap items-center justify-between gap-2 py-3"><span>{{ $document->document_number }} · v{{ $document->version_number }} · {{ $document->status->label() }}</span><a class="font-bold text-gold-600" href="{{ route('admin.customer-generated-documents.show',$document) }}">View</a></div>@empty<p class="text-sm text-neutral-500">No generated forms yet.</p>@endforelse</div></section>
@endsection
