<!doctype html>
<html><head><meta charset="utf-8"><style>
@page{size:A4;margin:12mm}body{font-family:DejaVu Sans;color:#252525;font-size:9px;line-height:1.35}.top{display:table;width:100%;border-bottom:3px solid #c89835;padding-bottom:8px}.cell{display:table-cell;vertical-align:top}.photo{width:85px;height:100px;object-fit:cover;border:1px solid #999}.placeholder{display:inline-block;width:85px;height:100px;border:1px solid #c89835;text-align:center;padding-top:38px;color:#a97718;font-weight:bold}.brand{font-size:19px;font-weight:bold;color:#a97718}.title{font-size:16px;font-weight:bold;color:#a97718;margin-top:5px}.section{margin-top:10px;border:1px solid #aaa;padding:7px}.section-title{font-size:11px;font-weight:bold;color:#a97718;border-bottom:1px solid #d9bf86;padding-bottom:3px;margin-bottom:5px;text-transform:uppercase}.grid{display:table;width:100%}.item{display:table-cell;width:50%;padding:2px 7px 2px 0}.label{font-size:8px;color:#666;text-transform:uppercase}.value{font-weight:bold}.table{width:100%;border-collapse:collapse}.table th,.table td{border:1px solid #aaa;padding:5px;text-align:left}.signature{height:45px;border-bottom:1px solid #555;width:180px}.stamp{max-width:75px;max-height:55px}.footer{margin-top:12px;display:table;width:100%}
</style></head><body>
@php($w=$snapshot['worker']??[])
<div class="top"><div class="cell" style="width:75%">@if($logoData)<img src="{{ $logoData }}" style="max-width:80px;max-height:35px"><br>@endif<div class="brand">{{ $snapshot['agency']['business_name']??'Helper Home' }}</div><div>{{ $snapshot['agency']['tagline']??'Home Care & Domestic Services' }}</div><div class="title">WORKER REGISTRATION FORM</div></div><div class="cell" style="width:25%;text-align:right">@if($photoData)<img class="photo" src="{{ $photoData }}">@else<span class="placeholder">PHOTO</span>@endif</div></div>
<div class="section"><div class="grid"><div class="item">Registration No:<br><span class="value">{{ $w['registration_number']??'—' }}</span></div><div class="item">Registration Date:<br><span class="value">{{ $w['registration_date']??'—' }}</span></div><div class="item">Worker Code:<br><span class="value">{{ $w['worker_code']??'—' }}</span></div></div></div>
<div class="section"><div class="section-title">Personal Details</div><div class="grid"><div class="item">Worker Name: <span class="value">{{ $w['name']??'—' }}</span></div><div class="item">Mobile: <span class="value">{{ $w['mobile_number']??'—' }}</span></div><div class="item">Alternate Mobile: <span class="value">{{ $w['alternate_mobile_number']??'—' }}</span></div><div class="item">Email: <span class="value">{{ $w['email']??'—' }}</span></div><div class="item">Address: <span class="value">{{ collect([$w['address_line_1']??null,$w['address_line_2']??null])->filter()->implode(', ') ?: '—' }}</span></div><div class="item">City / State / Pincode: <span class="value">{{ collect([$w['city']??null,$w['state']??null,$w['pincode']??null])->filter()->implode(', ') ?: '—' }}</span></div><div class="item">DOB / Age: <span class="value">{{ $w['date_of_birth']??'—' }} / {{ $w['age']??'—' }}</span></div><div class="item">Gender: <span class="value">{{ !empty($w['gender'])?str($w['gender'])->headline():'—' }}</span></div><div class="item">Marital Status: <span class="value">{{ !empty($w['marital_status'])?str($w['marital_status'])->headline():'—' }}</span></div><div class="item">Date of Joining: <span class="value">{{ $w['date_of_joining']??'—' }}</span></div></div></div>
<div class="section"><div class="section-title">Work / Professional Details</div><div>Services: @forelse($snapshot['services']??[] as $service)<strong>{{ $service['name'] }}</strong>@if(!$loop->last), @endif @empty—@endforelse</div><div class="grid"><div class="item">Experience: <span class="value">{{ $w['years_of_experience']??'—' }} years</span></div><div class="item">Preferred Duty: <span class="value">{{ $w['preferred_duty_type']??'—' }}</span></div><div class="item">Preferred Location: <span class="value">{{ $w['preferred_work_location']??'—' }}</span></div><div class="item">Expected Salary: <span class="value">{{ isset($w['salary_expectation'])&&$w['salary_expectation']!==null?'₹'.number_format((float)$w['salary_expectation'],2):'—' }}</span></div><div class="item">Availability: <span class="value">{{ !empty($w['availability_status'])?str($w['availability_status'])->headline():'—' }}</span></div><div class="item">Worker Status: <span class="value">{{ !empty($w['worker_status'])?str($w['worker_status'])->headline():'—' }}</span></div></div>{{ $w['experience_notes']??'' }}</div>
<div class="section"><div class="section-title">Identity / Verification Details</div><div class="grid"><div class="item">Identity Proof: <span class="value">@forelse($snapshot['identity_documents']??[] as $identity){{ $identity['document_name']?:str($identity['document_type'])->headline() }}@if(!$loop->last), @endif @empty—@endforelse</span></div><div class="item">Identity Proof Number: <span class="value">@forelse($snapshot['identity_documents']??[] as $identity){{ $identity['document_number']??'—' }}@if(!$loop->last), @endif @empty—@endforelse</span></div><div class="item">Concerned Police Station: <span class="value">{{ $snapshot['internal']['police_station_name']??'—' }}</span></div></div><div class="grid"><div class="item">Document Verification: {{ str($snapshot['verification']['document']??'pending')->headline() }}</div><div class="item">Police Verification: {{ str($snapshot['verification']['police']??'pending')->headline() }}</div><div class="item">Background Verification: {{ str($snapshot['verification']['background']??'pending')->headline() }}</div></div></div>
<div class="section"><div class="section-title">Internal Details</div><div class="grid"><div class="item">Supervisor: <span class="value">{{ $snapshot['internal']['supervisor_name']??'—' }}</span></div><div class="item">Executive: <span class="value">{{ $snapshot['internal']['executive_name']??'—' }}</span></div></div></div>
@php($referenceRows=max(5,count($snapshot['references']??[])))<div class="section"><div class="section-title">References</div><table class="table"><thead><tr><th>Sr.</th><th>Name</th><th>Mobile Number</th><th>Relation</th><th>Occupation</th></tr></thead><tbody>@for($i=0;$i<$referenceRows;$i++)@php($reference=$snapshot['references'][$i]??[])<tr><td>{{ $i+1 }}</td><td>{{ $reference['name']??'' }}</td><td>{{ $reference['mobile_number']??'' }}</td><td>{{ $reference['relation']??'' }}</td><td>{{ $reference['occupation']??'' }}</td></tr>@endfor</tbody></table></div>
<div class="footer"><div class="cell">Worker Signature:<div class="signature"></div><br>Date: __________________</div><div class="cell">Authorized Person: {{ $snapshot['agency']['authorized_person']??'—' }}<br><br>@if($signatureData)<img class="stamp" src="{{ $signatureData }}">@endif @if($stampData)<img class="stamp" src="{{ $stampData }}">@endif<br>Agency Signature / Stamp</div></div>
</body></html>
