<!doctype html>
<html><head><meta charset="utf-8"><style>
@page{size:A4;margin:16mm}body{font-family:DejaVu Sans;color:#252525;font-size:10px;line-height:1.4}.top{display:table;width:100%;border-bottom:3px solid #c89835;padding-bottom:12px}.cell{display:table-cell;vertical-align:top;width:70%}.photo-cell{width:30%;text-align:right}.logo{max-width:90px;max-height:45px}.photo{width:100px;height:120px;object-fit:cover;border:1px solid #ddd}.placeholder{display:inline-block;width:100px;height:120px;border:1px solid #c89835;text-align:center;padding-top:45px;color:#a97718;font-weight:bold}.brand{font-size:20px;color:#a97718;font-weight:bold}.title{font-size:18px;color:#a97718;font-weight:bold;margin-top:10px}.section{margin-top:15px;border:1px solid #ddd;padding:10px}.section-title{font-size:12px;font-weight:bold;color:#a97718;border-bottom:1px solid #e5d4ad;padding-bottom:4px;margin-bottom:7px;text-transform:uppercase}.grid{display:table;width:100%}.item{display:table-cell;width:50%;padding:3px 8px 3px 0}.label{color:#777;font-size:9px;text-transform:uppercase}.value{font-weight:bold}.pill{display:inline-block;border:1px solid #c89835;padding:3px 7px;margin:2px;border-radius:8px}.muted{color:#777}.footer{margin-top:18px;border-top:1px solid #ddd;padding-top:8px;color:#777;font-size:9px}
</style></head><body>
@php($w=$snapshot['worker']??[])
<div class="top"><div class="cell">@if($logoData)<img class="logo" src="{{ $logoData }}"><br>@endif<div class="brand">{{ $snapshot['agency']['business_name']??'Helper Home' }}</div><div>{{ $snapshot['agency']['tagline']??'Home Care & Domestic Services' }}</div><div class="title">WORKER PROFILE / RESUME</div></div><div class="photo-cell">@if($photoData)<img class="photo" src="{{ $photoData }}">@else<span class="placeholder">HELPER<br>HOME</span>@endif</div></div>
<div class="section"><div class="section-title">Worker Profile</div><div class="grid"><div class="item"><span class="label">Worker Code</span><br><span class="value">{{ $w['worker_code']??'—' }}</span></div><div class="item"><span class="label">Name</span><br><span class="value">{{ $w['name']??'—' }}</span></div><div class="item"><span class="label">Mobile</span><br><span class="value">{{ $w['mobile_number']??'—' }}</span></div><div class="item"><span class="label">City / State</span><br><span class="value">{{ collect([$w['city']??null,$w['state']??null])->filter()->implode(', ') ?: '—' }}</span></div></div></div>
<div class="section"><div class="section-title">Personal Details</div><div class="grid"><div class="item"><span class="label">Age / Date of Birth</span><br><span class="value">{{ $w['age']??'—' }} @if(!empty($w['date_of_birth'])) ({{ $w['date_of_birth'] }}) @endif</span></div><div class="item"><span class="label">Gender</span><br><span class="value">{{ !empty($w['gender'])?str($w['gender'])->headline():'—' }}</span></div><div class="item"><span class="label">Marital Status</span><br><span class="value">{{ !empty($w['marital_status'])?str($w['marital_status'])->headline():'—' }}</span></div><div class="item"><span class="label">Address</span><br><span class="value">{{ collect([$w['address_line_1']??null,$w['address_line_2']??null,$w['city']??null,$w['state']??null,$w['pincode']??null])->filter()->implode(', ') ?: '—' }}</span></div></div></div>
<div class="section"><div class="section-title">Professional Details</div><div><span class="label">Service Categories</span><br>@forelse($snapshot['services']??[] as $service)<span class="pill">{{ $service['name'] }}@if($service['experience_years'] !== null) · {{ $service['experience_years'] }} yrs @endif</span>@empty<span class="muted">—</span>@endforelse</div><div class="grid"><div class="item"><span class="label">Overall Experience</span><br><span class="value">{{ $w['years_of_experience']??'—' }} @if(isset($w['years_of_experience'])) years @endif</span></div><div class="item"><span class="label">Preferred Duty Type</span><br><span class="value">{{ $w['preferred_duty_type']??'—' }}</span></div><div class="item"><span class="label">Preferred Location</span><br><span class="value">{{ $w['preferred_work_location']??'—' }}</span></div><div class="item"><span class="label">Availability</span><br><span class="value">{{ !empty($w['availability_status'])?str($w['availability_status'])->headline():'—' }}</span></div><div class="item"><span class="label">Expected Salary</span><br><span class="value">{{ isset($w['salary_expectation'])&&$w['salary_expectation']!==null?'₹'.number_format((float)$w['salary_expectation'],2):'—' }}</span></div></div>@if(!empty($w['experience_notes']))<p><span class="label">Experience / Skills</span><br>{{ $w['experience_notes'] }}</p>@endif</div>
<div class="section"><div class="section-title">Verification</div><div class="grid"><div class="item">Document Verification: <strong>{{ str($snapshot['verification']['document']??'pending')->headline() }}</strong></div><div class="item">Police Verification: <strong>{{ str($snapshot['verification']['police']??'pending')->headline() }}</strong></div><div class="item">Background Verification: <strong>{{ str($snapshot['verification']['background']??'pending')->headline() }}</strong></div></div></div>
@if(!empty($snapshot['interview']))<div class="section"><div class="section-title">Interview Assessment</div><div class="grid"><div class="item">Result: <strong>{{ str($snapshot['interview']['result']??'pending')->headline() }}</strong></div><div class="item">Skills: {{ $snapshot['interview']['skills_assessment']??'—' }}</div><div class="item">Communication: {{ $snapshot['interview']['communication_assessment']??'—' }}</div></div></div>@endif
@if(!empty($snapshot['references']))<div class="section"><div class="section-title">References</div>@foreach($snapshot['references'] as $reference)<div>{{ $reference['name']??'—' }} · {{ $reference['relation']??'—' }} · {{ $reference['mobile_number']??'—' }}</div>@endforeach</div>@endif
<div class="footer">{{ $snapshot['agency']['business_name']??'Helper Home' }} · {{ $snapshot['agency']['phone']??'' }} · {{ $snapshot['agency']['email']??'' }}<br>{{ $snapshot['agency']['address']??'' }}</div>
</body></html>
