@extends('layouts.admin')
@php($labels=['workers'=>'Worker Reports','customers'=>'Customer Reports','requirements'=>'Requirement Reports','assignments'=>'Assignment Reports','replacements'=>'Replacement Reports','agreements'=>'Agreement Reports','invoices'=>'Invoice Reports','payments'=>'Payment Reports','outstanding'=>'Outstanding Payment Report','documents'=>'Document Reports'])
@section('title',$labels[$report] ?? 'Report')
@section('heading',$labels[$report] ?? 'Report')
@section('subheading','Filtered live records with CSV export.')
@section('actions')@if(in_array($report,['workers','customers','requirements','assignments','invoices','payments']))<a class="btn-secondary" href="{{ route('admin.reports.'.$report.'.export',request()->query()) }}">Export CSV</a>@endif @endsection
@section('content')
<form class="card mb-6 grid gap-3 p-4 md:grid-cols-4" method="GET"><label class="text-sm font-semibold">Quick range<select name="quick" class="mt-1 block w-full"><option value="">Custom</option>@foreach(['today'=>'Today','yesterday'=>'Yesterday','week'=>'This Week','month'=>'This Month','last_month'=>'Last Month','financial_year'=>'This Financial Year'] as $v=>$l)<option value="{{ $v }}" @selected(request('quick')===$v)>{{ $l }}</option>@endforeach</select></label><label class="text-sm font-semibold">Start date<input type="date" name="start_date" value="{{ request('start_date') }}"></label><label class="text-sm font-semibold">End date<input type="date" name="end_date" value="{{ request('end_date') }}"></label><label class="text-sm font-semibold">Status<input name="status" value="{{ request('status') }}" placeholder="Status"></label><label class="text-sm font-semibold">Customer ID<input name="customer_id" value="{{ request('customer_id') }}"></label><label class="text-sm font-semibold">Worker ID<input name="worker_id" value="{{ request('worker_id') }}"></label>@if(in_array($report,['invoices','outstanding']))<label class="text-sm font-semibold">Payment status<input name="payment_status" value="{{ request('payment_status') }}" placeholder="paid, unpaid, overdue"></label>@endif @if($report==='outstanding')<label class="mt-6 text-sm font-semibold"><input type="checkbox" name="overdue_only" value="1" @checked(request('overdue_only'))> Overdue only</label>@endif<div><button class="btn-primary mt-5">Filter</button></div></form>
<div class="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">@foreach($data['summary'] as $label=>$value)<article class="card p-4"><p class="text-sm text-neutral-500">{{ $label }}</p><p class="mt-1 text-2xl font-black">{{ is_numeric($value) && in_array($report,['invoices','outstanding','payments']) && !in_array($label,['Invoice Count','Completed Payments']) ? '₹'.number_format((float)$value,2) : number_format((float)$value) }}</p></article>@endforeach</div>
<div class="card overflow-x-auto"><table class="w-full min-w-[1100px] text-left text-sm"><thead><tr>@foreach($data['columns'] as $column)<th class="p-3">{{ $column }}</th>@endforeach</tr></thead><tbody class="divide-y">@forelse($data['rows'] as $row)<tr>@foreach(app(App\Services\ReportService::class)->displayRow($report,$row) as $value)<td class="p-3">{{ $value === null || $value === '' ? '—' : $value }}</td>@endforeach</tr>@empty<tr><td colspan="{{ count($data['columns']) }}" class="p-8 text-center text-neutral-500">No records found for the selected filters.</td></tr>@endforelse</tbody></table></div><div class="mt-4">{{ $data['rows']->links() }}</div>
@if($report==='workers' && isset($data['utilization']))<section class="card mt-8 overflow-x-auto"><h2 class="border-b p-4 font-black">Worker Utilization</h2><table class="w-full min-w-[700px] text-left text-sm"><thead><tr><th class="p-3">Worker</th><th class="p-3">Total Assignments</th><th class="p-3">Completed</th><th class="p-3">Current Status</th><th class="p-3">Current Assignment</th><th class="p-3">Replacement Count</th></tr></thead><tbody class="divide-y">@forelse($data['utilization'] as $worker)<tr><td class="p-3">{{ $worker->name }}</td><td>{{ $worker->assignments_count }}</td><td>{{ $worker->completed_assignments_count }}</td><td>{{ $worker->availability_status?->value }}</td><td>{{ $worker->assignments->first()?->assignment_code ?: '—' }}</td><td>{{ $worker->replacement_count }}</td></tr>@empty<tr><td colspan="6" class="p-4 text-neutral-500">No workers found.</td></tr>@endforelse</tbody></table></section>@endif
@endsection
