@extends('layouts.admin')
@section('title','Reports Overview')
@section('heading','Reports Overview')
@section('subheading','Live operational and financial analytics from existing records.')
@section('content')
<form class="card mb-6 flex flex-wrap items-end gap-3 p-4" method="GET"><label class="text-sm font-semibold">Quick range<select name="quick" class="mt-1 block"><option value="">Custom</option>@foreach(['today'=>'Today','yesterday'=>'Yesterday','week'=>'This Week','month'=>'This Month','last_month'=>'Last Month','financial_year'=>'This Financial Year'] as $v=>$l)<option value="{{ $v }}" @selected(request('quick')===$v)>{{ $l }}</option>@endforeach</select></label><label class="text-sm font-semibold">Start date<input type="date" name="start_date" value="{{ request('start_date',$data['range'][0]->toDateString()) }}"></label><label class="text-sm font-semibold">End date<input type="date" name="end_date" value="{{ request('end_date',$data['range'][1]->toDateString()) }}"></label><button class="btn-primary">Apply</button></form>
<p class="mb-4 text-sm text-neutral-500">Snapshot metrics reflect current records. Activity metrics use {{ $data['range'][0]->format('d M Y') }} to {{ $data['range'][1]->format('d M Y') }}.</p>
<div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">@foreach($data['snapshot'] as $label=>$value)<article class="card p-5"><p class="text-sm text-neutral-500">{{ $label }}</p><p class="mt-2 text-2xl font-black">@if(str_contains($label,'Amount') || str_contains($label,'Payments') || $label==='Invoice Amount')₹{{ number_format((float)$value,2) }}@else{{ number_format((float)$value) }}@endif</p></article>@endforeach</div>
<h2 class="mb-3 mt-8 text-xl font-black">Selected Range Activity</h2><div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">@foreach($data['activity'] as $label=>$value)<article class="card p-5"><p class="text-sm text-neutral-500">{{ $label }}</p><p class="mt-2 text-2xl font-black">{{ str_contains($label,'Payments') ? '₹'.number_format((float)$value,2) : number_format((float)$value) }}</p></article>@endforeach</div>
<div class="mt-8 grid gap-6 lg:grid-cols-3"><section class="card p-5"><h2 class="mb-3 font-black">Service Demand</h2>@forelse($data['serviceDemand'] as $item)<div class="flex justify-between border-b py-2 text-sm"><span>{{ $item->name }}</span><strong>{{ $item->total }}</strong></div>@empty<p class="text-sm text-neutral-500">No requirements in this range.</p>@endforelse</section><section class="card p-5"><h2 class="mb-3 font-black">Duty Type Demand</h2>@forelse($data['dutyDemand'] as $item)<div class="flex justify-between border-b py-2 text-sm"><span>{{ $item->name }}</span><strong>{{ $item->total }}</strong></div>@empty<p class="text-sm text-neutral-500">No duty data in this range.</p>@endforelse</section><section class="card p-5"><h2 class="mb-3 font-black">Payment Modes</h2>@forelse($data['paymentModes'] as $item)<div class="flex justify-between border-b py-2 text-sm"><span>{{ str($item->payment_mode)->replace('_',' ')->headline() }}</span><strong>₹{{ number_format((float)$item->total,2) }}</strong></div>@empty<p class="text-sm text-neutral-500">No completed payments in this range.</p>@endforelse</section></div>
@endsection
