@extends('layouts.admin')
@section('title', 'Documents')
@section('heading', 'Document Center')
@section('subheading', 'Search generated business documents across the portal.')
@section('content')
<div class="mb-4 flex flex-wrap gap-2"><a class="btn-secondary" href="{{ route('admin.documents.index',['quick'=>'today']) }}">Today</a><a class="btn-secondary" href="{{ route('admin.documents.index',['quick'=>'week']) }}">This Week</a><a class="btn-secondary" href="{{ route('admin.documents.index',['quick'=>'month']) }}">This Month</a></div>
<form class="card mb-5 grid gap-3 p-4 md:grid-cols-3" method="GET"><input name="search" placeholder="Document, customer, mobile, worker code" value="{{ request('search') }}"><select name="document_type"><option value="">All document types</option>@foreach(['worker_resume'=>'Worker Resume','worker_registration_form'=>'Worker Registration Form','customer_registration_form'=>'Customer Registration Form','agreement'=>'Agreement','invoice'=>'Invoice','payment_receipt'=>'Payment Receipt'] as $value=>$label)<option value="{{ $value }}" @selected(request('document_type')===$value)>{{ $label }}</option>@endforeach</select><select name="status"><option value="">All statuses</option>@foreach(['draft','generated','shared','archived','sent','signed','active','cancelled'] as $status)<option value="{{ $status }}" @selected(request('status')===$status)>{{ str($status)->headline() }}</option>@endforeach</select><select name="customer_id"><option value="">All customers</option>@foreach($customers as $customer)<option value="{{ $customer->id }}" @selected(request('customer_id')==$customer->id)>{{ $customer->name }}</option>@endforeach</select><select name="worker_id"><option value="">All workers</option>@foreach($workers as $worker)<option value="{{ $worker->id }}" @selected(request('worker_id')==$worker->id)>{{ $worker->name }}</option>@endforeach</select><div class="flex gap-2"><input type="date" name="from" value="{{ request('from') }}"><input type="date" name="to" value="{{ request('to') }}"><button class="btn-primary">Filter</button></div></form>
<div class="card max-w-full overflow-x-auto"><table class="w-full min-w-[1100px] text-left text-sm"><thead><tr>@foreach(['Document','Document Number','Related Person','Related Code','Type','Generated Date','Status','Actions'] as $header)<th class="p-3">{{ $header }}</th>@endforeach</tr></thead><tbody class="divide-y">@forelse($documents as $document)<tr><td class="p-3 font-bold">{{ str($document['document_type'])->replace('_',' ')->headline() }}</td><td>{{ $document['document_number'] ?: '—' }}</td><td>{{ $document['related_name'] ?: '—' }}</td><td>{{ $document['related_code'] ?: '—' }}</td><td>{{ str($document['document_type'])->replace('_',' ')->headline() }}</td><td>{{ $document['generated_at']?->format('d M Y, h:i A') ?: '—' }}</td><td>{{ str($document['status'])->replace('_',' ')->headline() }}</td><td class="whitespace-nowrap">@if($document['source_type']==='worker')<a href="{{ route('admin.worker-generated-documents.show',$document['source_id']) }}">View</a> @if(auth()->user()->hasPermission('worker-resumes.download')||auth()->user()->hasPermission('worker-registration-documents.download'))· <a href="{{ route('admin.worker-generated-documents.download',$document['source_id']) }}">Download</a>@endif @elseif($document['source_type']==='customer')<a href="{{ route('admin.customer-generated-documents.show',$document['source_id']) }}">View</a> · <a href="{{ route('admin.customer-generated-documents.download',$document['source_id']) }}">Download</a>@elseif($document['source_type']==='agreement')<a href="{{ route('admin.agreements.show',$document['source_id']) }}">View</a> · <a href="{{ route('admin.agreements.download',$document['source_id']) }}">Download</a>@elseif($document['source_type']==='invoice')<a href="{{ route('admin.invoices.show',$document['source_id']) }}">View</a> · <a href="{{ route('admin.invoices.download',$document['source_id']) }}">Download</a>@else<a href="{{ route('admin.payment-receipts.show',$document['source_id']) }}">View</a> · <a href="{{ route('admin.payment-receipts.download',$document['source_id']) }}">Download</a>@endif</td></tr>@empty<tr><td colspan="8" class="p-6 text-center text-neutral-500">No documents found.</td></tr>@endforelse</tbody></table></div><div class="mt-4">{{ $documents->links() }}</div>
@endsection
