<!doctype html><html><head><meta charset="utf-8"><style>
@page{size:A4;margin:13mm}body{font-family:DejaVu Sans;color:#252525;font-size:9px;line-height:1.35}.top{display:table;width:100%;border-bottom:3px solid #c89835;padding-bottom:9px}.cell{display:table-cell;vertical-align:top}.brand{font-size:20px;font-weight:bold;color:#a97718}.title{font-size:16px;font-weight:bold;color:#a97718;margin-top:5px}.section{margin-top:10px;border:1px solid #aaa;padding:8px}.section-title{font-size:11px;font-weight:bold;color:#a97718;border-bottom:1px solid #d9bf86;padding-bottom:3px;margin-bottom:6px;text-transform:uppercase}.grid{display:table;width:100%}.item{display:table-cell;width:50%;padding:2px 8px 2px 0}.label{font-size:8px;color:#666;text-transform:uppercase}.value{font-weight:bold}.note{white-space:pre-line}.check{display:inline-block;margin-right:12px}.signature{height:40px;border-bottom:1px solid #555;width:180px}.asset{max-width:95px;max-height:45px}
</style></head><body>
@php($c=$snapshot['customer']??[])
@php($r=$snapshot['requirement']??[])
@php($h=$snapshot['household']??[])
@php($a=$snapshot['accommodation']??[])
@php($w=$snapshot['working']??[])
@php($p=$snapshot['worker_preferences']??[])
<div class="top"><div class="cell" style="width:75%">@if($logoData)<img class="asset" src="{{ $logoData }}"><br>@endif<div class="brand">{{ $snapshot['agency']['business_name']??'Helper Home' }}</div><div>{{ $snapshot['agency']['tagline']??'Home Care & Domestic Services' }}</div><div class="title">CUSTOMER REGISTRATION FORM</div></div><div class="cell" style="width:25%;text-align:right">Customer ID:<br><strong>{{ $c['customer_code']??'—' }}</strong><br>Requirement ID:<br><strong>{{ $r['requirement_code']??'—' }}</strong><br>Document No:<br><strong>{{ $document->document_number??'Preview' }}</strong></div></div>
<div class="section"><div class="section-title">1. Customer Details</div><div class="grid"><div class="item">Customer Name: <span class="value">{{ $c['name']??'—' }}</span></div><div class="item">Mobile: <span class="value">{{ $c['mobile_number']??'—' }}</span></div><div class="item">Alternate Mobile: <span class="value">{{ $c['alternate_mobile_number']??'—' }}</span></div><div class="item">Email: <span class="value">{{ $c['email']??'—' }}</span></div><div class="item">Location: <span class="value">{{ $c['location']??'—' }}</span></div><div class="item">Registration Date: <span class="value">{{ $c['registration_date']??'—' }}</span></div><div class="item">Address: <span class="value">{{ collect([$c['address_line_1']??null,$c['address_line_2']??null])->filter()->implode(', ') ?: '—' }}</span></div><div class="item">City / State / Pincode: <span class="value">{{ collect([$c['city']??null,$c['state']??null,$c['pincode']??null])->filter()->implode(', ') ?: '—' }}</span></div></div></div>
<div class="section"><div class="section-title">2. Service Requirement</div><div class="grid"><div class="item">Service Category: <span class="value">{{ $r['service_name']??'—' }}{{ $r['other_service_description']?' · '.$r['other_service_description']:'' }}</span></div><div class="item">Required Person: <span class="value">{{ $r['required_gender']?str($r['required_gender'])->replace('_',' ')->headline():'—' }}</span></div><div class="item">Number of Persons: <span class="value">{{ $r['number_of_persons']??'—' }}</span></div><div class="item">Duty Type: <span class="value">{{ $r['duty_type']??$r['custom_duty_type']??'—' }}</span></div><div class="item">Preferred Start: <span class="value">{{ $r['preferred_start_date']??'—' }}</span></div><div class="item">Preferred End: <span class="value">{{ $r['preferred_end_date']??'—' }}</span></div></div></div>
<div class="section"><div class="section-title">3. Salary & Agency Charge</div><div class="grid"><div class="item">Monthly Salary / Wage Budget: <span class="value">{{ $r['monthly_salary_budget']!==null?'₹'.number_format((float)$r['monthly_salary_budget'],2):'—' }}</span></div><div class="item">Monthly Agency Service Charge: <span class="value">{{ $r['monthly_agency_service_charge']!==null?'₹'.number_format((float)$r['monthly_agency_service_charge'],2):'—' }}</span></div></div></div>
<div class="section"><div class="section-title">4. House & Family Details</div><div class="grid"><div class="item">House Type: <span class="value">{{ $h['custom_house_type']??($h['house_type']?str($h['house_type'])->replace('_',' ')->upper():'—') }}</span></div><div class="item">Family Members: <span class="value">{{ $h['total_family_members']??'—' }}</span></div><div class="item">Adults / Children: <span class="value">{{ $h['adults_count']??'—' }} / {{ $h['children_count']??'—' }}</span></div><div class="item">Elderly / Patients: <span class="value">{{ $h['elderly_count']??'—' }} / {{ $h['patients_count']??'—' }}</span></div><div class="item">Food Preference: <span class="value">{{ $h['food_preference']?str($h['food_preference'])->replace('_',' ')->headline():'—' }}</span></div></div><p class="note"><span class="label">Detailed Work Description</span><br>{{ $r['detailed_work_description']??'—' }}</p><p class="note"><span class="label">Special Instructions / Responsibilities</span><br>{{ $r['special_instructions']??'—' }}</p></div>
<div class="section"><div class="section-title">5. Accommodation & Food</div><div class="grid"><div class="item">Accommodation: <span class="value">{{ $a['accommodation_provided']?str($a['accommodation_provided'])->headline():'—' }}</span></div><div class="item">Room / Bathroom: <span class="value">{{ collect([$a['room_type']??null,$a['bathroom_type']??null])->filter()->map(fn($v)=>str($v)->headline())->implode(' / ') ?: '—' }}</span></div><div class="item">Food Provided: <span class="value">{{ $a['food_provided']?str($a['food_provided'])->headline():'—' }}</span></div><div class="item">Meals: <span class="value">{{ collect(['Breakfast'=>$a['breakfast_provided']??false,'Lunch'=>$a['lunch_provided']??false,'Dinner'=>$a['dinner_provided']??false,'Tea/Snacks'=>$a['tea_snacks_provided']??false])->filter()->keys()->implode(', ') ?: '—' }}</span></div></div><p>{{ $a['other_food_details']??'' }}<br>{{ $a['accommodation_notes']??'' }}</p></div>
<div class="section"><div class="section-title">6. Working Hours & Daily Routine</div><div class="grid"><div class="item">Duty / Working Hours: <span class="value">{{ $w['working_hours_text']??'—' }}</span></div><div class="item">Start / End: <span class="value">{{ collect([$w['work_start_time']??null,$w['work_end_time']??null])->filter()->implode(' - ') ?: '—' }}</span></div><div class="item">Wake-Up / Sleeping: <span class="value">{{ collect([$w['expected_wakeup_time']??null,$w['expected_sleep_time']??null])->filter()->implode(' / ') ?: '—' }}</span></div><div class="item">Afternoon Rest: <span class="value">{{ is_null($w['afternoon_rest']??null)?'—':($w['afternoon_rest']?'Yes':'No') }} {{ $w['rest_duration_hours']??'' }}</span></div><div class="item">Monthly Off / Leave: <span class="value">{{ $w['monthly_leave_days']??'—' }}</span></div><div class="item">Night Duty: <span class="value">{{ is_null($w['night_duty_required']??null)?'—':($w['night_duty_required']?'Yes':'No') }}</span></div><div class="item">Early Morning Work: <span class="value">{{ is_null($w['early_morning_work_required']??null)?'—':($w['early_morning_work_required']?'Yes':'No') }}</span></div></div><p>{{ $w['leave_details']??'' }}<br>{{ $w['early_morning_work_details']??'' }}</p></div>
<div class="section"><div class="section-title">7. Household Environment</div><div class="grid">@foreach([['Pets at Home','pets_at_home'],['Children at Home','children_at_home'],['Elderly at Home','elderly_at_home'],['Patient / Special Care','patient_care_required'],['Lift Available','lift_available'],['Outside Travel Required','outside_travel_required']] as [$label,$key])<div class="item">{{ $label }}: <span class="value">{{ is_null($h[$key]??null)?'—':($h[$key]?'Yes':'No') }}</span></div>@endforeach</div></div>
<div class="section"><div class="section-title">8. Worker Preferences</div><div class="grid"><div class="item">Preferred Age: <span class="value">{{ ($p['preferred_age_min']??null)!==null||($p['preferred_age_max']??null)!==null ? (($p['preferred_age_min']??'Any').' - '.($p['preferred_age_max']??'Any')) : '—' }}</span></div><div class="item">Experience: <span class="value">{{ $p['experience_requirement']?str($p['experience_requirement'])->replace('_',' ')->headline():'—' }}</span></div><div class="item">Language: <span class="value">{{ $p['language_preference']??'—' }}</span></div><div class="item">Specific Skills: <span class="value">{{ $p['specific_skills']??'—' }}</span></div></div><p>{{ $p['other_work_expected']??'' }}<br>{{ $p['worker_preference_notes']??'' }}</p></div>
<div class="section"><div class="grid"><div class="item">Customer Signature:<div class="signature"></div>Date: __________________</div><div class="item">Authorized Person: {{ $snapshot['agency']['authorized_person']??'—' }}<br>@if($signatureData)<img class="asset" src="{{ $signatureData }}">@endif @if($stampData)<img class="asset" src="{{ $stampData }}">@endif<br>Agency Signature / Stamp<br>Date: __________________</div></div></div>
</body></html>
